### ISSUE TITLE
refreshClusters() on custom markers

### ISSUE THREAD

**Issue by pedrobrost** [YUzhva/react-leaflet-markercluster#100]
Hi, I can't find any way to refresh the cluster custom icon when there is an update in the state. I don't understand how to call the refreshClusters() function (http://leaflet.github.io/Leaflet.markercluster/#refreshing-the-clusters-icon)

Thanks!

**Comment by YUzhva** [comment]
`markers` are available during the click event, like:

```javascript
<MarkerClusterGroup
  onClusterClick={(cluster) => {
    // markers somwhere inside cluster obj
  }}
>
```

can you, please, provide your example for a better understanding of the issue?

**Comment by pedrobrost** [comment]
My problem is that when there is an update in my state that should change my cluster icon, the "iconCreateFunction" isn't called again, so my cluster icons ramains the same. I think I found a solution, it works but I don't know if it is the best way to do it:

```js
  <MarkerClusterGroup
    iconCreateFunction={createClusterIcon}
    ref={markerClusterGroup => {
      if (markerClusterGroup) {
        markerClusterGroup.leafletElement.refreshClusters(); // This updates cluster icons
      }
    }}
  >
    {props.markers.map(marker => (
      <Marker
        icon={createIcon(marker)}
        key={marker.id}
        position={marker.location.coordinates}
      />
    ))}
  </MarkerClusterGroup>
```

**Comment by lucianolorenti** [comment]
I was having the same issue. I have some markers and some data according the date. When you select a date, a set of markers with different values are fetched.  
I used the code of pedrobrost and did not work for me, and I couldn't figure out why.
Apparently, when the key of the Marker is repeated, the `getAllChildMarkers` returns, what I think is the previous data, or perhaps the original Marker data with that key.
Changing the key worked for me.

**Comment by kempjeng** [comment]
> I was having the same issue. I have some markers and some data according the date. When you select a date, a set of markers with different values are fetched.
> I used the code of pedrobrost and did not work for me, and I couldn't figure out why.
> Apparently, when the key of the Marker is repeated, the `getAllChildMarkers` returns, what I think is the previous data, or perhaps the original Marker data with that key.
> Changing the key worked for me.

Nice work @lucianolorenti.  I have an issue where due to the new key I'm getting multiple renders of the same markers 

combining your solution of changing the key with:

```jsx
<MarkerClusterGroup
    iconCreateFunction={createClusterIcon}
    ref={clusterRef => {
      if (clusterRef) {
        clusterRef.current.leafletElement.refreshClusters();
      }
    }}
  >
```

fixed the issue for me

**Comment by TimMcCauley** [comment]
Related https://github.com/yuzhva/react-leaflet-markercluster/issues/149#issuecomment-854920761
