### ISSUE TITLE
UMD builds don't work as standalone scripts

### ISSUE THREAD

**Issue by timkelty** [yuzhva/react-leaflet-markercluster#101]
I'm trying to set up a test on Codepen using, but the unpkg UMD builds aren't wrapped so you end up with `exports is not defined`, `require is not defined` etc.

**Comment by YUzhva** [comment]
Hey hi, @timkelty 

Please, CodeSandbox Getting Started has been created:
https://codesandbox.io/s/react-leaflet-markercluster-getting-started-9binx
