### ISSUE TITLE
iconCreateFunction prop not working

### ISSUE THREAD

**Issue by Sokal21** [YUzhva/react-leaflet-markercluster#102]
I'm using `iconCreateFunction` prop for customizing the cluster icon but is not wrking. This is the code I'm using

![image](https://user-images.githubusercontent.com/18652696/75550162-0fd7d100-5a10-11ea-93e0-f77f737c76fb.png)

The icon is not renderer as expected an nothing is outputed in the console.

**Comment by YUzhva** [comment]
Probably that is because opening `<span>` tag has been missed from `html` key in `new DivIcon({})`.

**Comment by Sokal21** [comment]
It is not that, the function is not called. There is nothing logged in then console.

**Comment by YUzhva** [comment]
Here is CodeSandbox:
https://codesandbox.io/s/react-leaflet-markercluster-issues102-7fsz8

`iconCreateFunction` works well.

Please, try to move `require('leaflet')` outside the scope of `clusterIconCreateFunction`

**Comment by YUzhva** [comment]
@Sokal21 

NOTE: `divIcon` from 'leaflet' - first letter is lower case.
