### ISSUE TITLE
Spiderfy cluster closes onClick

### ISSUE THREAD

**Issue by hdehal** [yuzhva/react-leaflet-markercluster#105]
Clustering seems to work beautifully, and if I click on one of the cluster `CircleMarker` or `Tooltip` it opens a new link (which I have as an onClick), but unfortunately the cluster spiderfy closes.

So if the user wants to click other links, they need to reopen (and re-spiderfy) the cluster, and rinse and repeat. 

**Is there any way to keep the spiderfy open onClick, and close it on zoom out (the latter which already behaves correctly)?**

E.g. clicking "Huckberry" will open a new link, close the tooltip:

![image](https://i.stack.imgur.com/eSEiU.png)

But unfortunately the cluster will also close and spiderfy after clicking the onClick link:

![image](https://i.stack.imgur.com/5tqUx.png)

Thank you!

**Comment by YUzhva** [comment]
hey hi, @hdehal 

This repo - is just a wrapper of https://github.com/Leaflet/Leaflet.markercluster to React.

Not features have been provided here.
So, this question is related to the repo: https://github.com/Leaflet/Leaflet.markercluster

I did not have such a scenario for dealing in such a way with clusters.
