### ISSUE TITLE
No way to set popup options

### ISSUE THREAD

**Issue by jared-dykstra** [YUzhva/react-leaflet-markercluster#11]
Currently, there is no way to set the leaflet options on a popup or tooltip.  For example, the width of a leaflet popup can be specified:  http://leafletjs.com/reference.html#popup-options

Proposed changes in #10

**Comment by YUzhva** [comment]
Hey hi (=
Looks like I need to improve under documentation improvement...

One of the ways how you could set marker options, it's passing not just a string to marker popup key - create Leaflet popup according to Leaflet documentation and pass it instead of string.

Full example:
```javascript
const markers = [
  {lat: 49.8397, lng: 24.0297, popup: getBasicPopup('clustered'), options: {icon: redMarker}},
  {lat: 50.4501, lng: 30.5234},
  {lat: 52.2297, lng: 21.0122},
  {lat: 50.0647, lng: 19.9450},
  {lat: 48.9226, lng: 24.7111},
  {lat: 48.7164, lng: 21.2611},
  {lat: 51.5, lng: -0.09, popup: getLeafletPopup('lonely')},
];

function getLeafletPopup(name) {
  return L.popup({minWidth: 200})
    .setContent(`
      <div>
        <b>Hello world!</b>
        <p>I am a ${name} popup.</p>
      </div>
    `);
}

function getBasicPopup(name) {
  return (`
    <div>
      <b>Hello world!</b>
      <p>I am a ${name} popup.</p>
    </div>
  `);
}
```

Is it that what you was looking for?

**Comment by jared-dykstra** [comment]
I wasn't aware that you could return a L.popup(), so thanks for the explanation.  I refactored my code and it works reasonably well.  However, I did notice I couldn't use deferred execution when returning a L.popup() instance even though I could do that when returning a string

```
// Does not work
{lat: 51.5, lng: -0.09, popup: () => L.popup({...)).setContent('...')}
// Does work
{lat: 51.5, lng: -0.09, popup: L.popup({...)).setContent('...')}
```

I'll close this issue

**Comment by YUzhva** [comment]
Update: Added [API section](https://github.com/YUzhva/react-leaflet-markercluster#api) in [release] 1.1.2: Update readme and dependency (#14)
