### ISSUE TITLE
Does react-leaflet-markercluster requires React 16.3 ?

### ISSUE THREAD

**Issue by Neofield-Dylan** [yuzhva/react-leaflet-markercluster#112]
An error occurs when I try to import react-leaflet-markercluster:
`TypeError: __webpack_require__.i(...) is not a function`

I am sure that occurs when I try to import this lib, because, when I comment it, the error disappear.
My package.json has:

```
    "leaflet": "^1.6.0",
    "leaflet.markercluster": "^1.4.1",
    "prop-types": "^15.7.2",
    "react": "^15.6.2",
    "react-dom": "15.4.2",
    "react-leaflet": "^2.6.0",
    "react-leaflet-markercluster": "^2.0.0",
```

So, I am already using lastest version of react-leaflet-markercluster which should work with react-leaflet v2. And I have all peer-dependencies installed. So, my guest is that maybe I need to upgrade react to 16. Can someone confirm that ?

By the way: I get to that conclusion because I looked into the debug screen in mozilla, and find the error occurs in this line:

`var leafletContext = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_react__["createContext"])({});`

Then, I google it and found this stackoverflow answer (https://stackoverflow.com/questions/51825251/call-to-createcontext-in-react-leaflet-es-context-js-fails).

**Comment by yuzhva** [comment]
React `15.x` does not support context, which is required by v2 of `react-leaflet`.

`reactt-leaflet` requires react `^16.8.0`
https://github.com/PaulLeCam/react-leaflet/blob/master/package.json#L59

**Comment by Neofield-Dylan** [comment]
Thanks for the information, man!
