### ISSUE TITLE
[iconCreateFunction] Pass dynamic function

### ISSUE THREAD

**Issue by tarun1992** [yuzhva/react-leaflet-markercluster#117]
Hi, Is there any way that I can pass conditional custom icon like 
`				iconCreateFunction={ renderIcon ? createClusterColorIcon : createClusterCustomIcon}
`
I tried this but it never re-renders the other icon. I am updating the state of renderIcon on click of a button but it doesn't re-render the other icon.  RenderIcon is a state which gets changed when clicking on the button.
Code - 
```
`
	useEffect(() => {
			setRenderIcon(true);
		}
	},[renderIcon])`
```
`<MarkerClusterGroup
				iconCreateFunction={ renderIcon ? createClusterColorIcon : createClusterCustomIcon}
				maxClusterRadius={25}>`
Any other way I can achieve this. Any help would be appreciated.

**Comment by frafra** [comment]
@yuzhva It looks like this stale bot is not working, or it has been deactivated, so this issue should be manually reopened somehow.

**Comment by frafra** [comment]
Not stale. Still relevant.

**Comment by frafra** [comment]
Still relevant.

**Comment by frafra** [comment]
Still relevant,

**Comment by frafra** [comment]
Up.

**Comment by lkostrowski** [comment]
Same here 

My function takes condidational arguments, so marker icon can be grayed on some cases, but it doesnt rerender.
I will try to look into this and maybe I will find a fix

**Comment by frafra** [comment]
I am no JavaScript or React expert, so I hope someone else with more experience could take the responsibility for maintaining this repository. If no-one is interested, I can do it, but it would be also nice if the author of this repository could add a link to the fork to a maintained alternative and put this repository in read-only mode.

**Comment by lkostrowski** [comment]
I can do it on my own and we can merge your PRs and probably update it to support Leaflet 1.8

But I agree that author should speak first, @yuzhva are you there :)

**Comment by frafra** [comment]
Still valid.

**Comment by frafra** [comment]
Still valid.
