### ISSUE TITLE
[question] How to use with features loaded from GeoJSON?

### ISSUE THREAD

**Issue by roata** [yuzhva/react-leaflet-markercluster#121]
Hi, I am attempting to use this plugin to improve the way maps are rendered on a site that tracks public transport in Moldova: https://github.com/roataway/roataway-web

We use `react-leaflet` to render the stations of a route, which are [loaded from GeoJSON](https://github.com/roataway/roataway-web/blob/88569747649b3eb9ec18107e7dca06d995f786c2/src/components/routes-stations.component.tsx). This works in principle, but on the UI side [it looks too cluttered](https://github.com/roataway/roataway-web/issues/85): 
![image](https://user-images.githubusercontent.com/48152696/95074320-9ffc9800-070e-11eb-8a38-92c4f87d1c90.png)

So naturally, your clustering plugin is a good fit. In the documentation you explain how to apply it when the markers are created explicitly. However, in our case we don't operate with markers directly, but we get them "automagically" through Leaflet's GeoJSON functionality.

Is there a way to use `react-leaflet-markercluster` with GeoJSON features?

**Comment by yuzhva** [comment]
Hey hi @roata 

Did you try just to wrap `<GeoJSON />` inside <MarkerClusterGroup /> component (right after <TileLayer />), like so:
```javascript
<Map center={this.state.center} zoom={8}>
  <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" maxZoom={18} />

    <MarkerClusterGroup>
      <GeoJSON
        data={geojson}
        onEachFeature={this.onEachFeature}
        pointToLayer={this.pointToLayer}
      />
    </MarkerClusterGroup>

</Map>
```

P.S: the original answer is posted here:
https://github.com/yuzhva/react-leaflet-markercluster/issues/69#issuecomment-389567907

**Comment by yuzhva** [comment]
@roata Could you, please, close that issue if this solution works for you?

**Comment by ehowey** [comment]
I can confirm this "solution" worked for me, this was naturally the first thing I tried with my GeoJson.  Great work on this package @yuzhva!

For reference it looks like this in my map:

```js
<FeatureGroup ref={groupRef} name="Services">
        {mappedResults.length > 0 && (
          <MarkerClusterGroup>
            <GeoJSON
              data={mappedResults}
              key={geoJsonKey}
              onEachFeature={createPopups}
            />
          </MarkerClusterGroup>
        )}
      </FeatureGroup>
```
