### ISSUE TITLE
Not compatible with react-leaflet v3?

### ISSUE THREAD

**Issue by barbalex** [yuzhva/react-leaflet-markercluster#123]
I tried upgrading my project to react-leaflet v3.0.0.

This is the component I tested: https://github.com/barbalex/apf2/blob/3c90de3a89c23ac720ccae00dc9bdedb71cfd6d0/src/components/Projekte/Karte/layers/Pop/index.js#L166-L175

It works well with react-leaflet v2.8.0 and react-leaflet-markercluster v2.0.0.

It breaks when using react-leaflet v3.0.0, causing this error:
<img width="841" alt="mk-error 2" src="https://user-images.githubusercontent.com/669783/97897491-da217f80-1d36-11eb-90e3-0c1141e38c77.png">
<img width="643" alt="mk-error" src="https://user-images.githubusercontent.com/669783/97897192-6ed7ad80-1d36-11eb-8f74-1999c1b1551d.png">

I guess this is not surprising as react-leaflet v3 [is a complete rewrite](https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v300-2020-10-31). For instance, [accessing the map has changed](https://react-leaflet.js.org/docs/api-map#usemap).

**Comment by yuzhva** [comment]
Hey hi, @barbalex 

Thank you for creating the issue.
I did not know, that `v3.0.0` of `react-leaflet` has been released.

Don't know, how long the migration to v3 could take.

Would read the v3 documentation during those weekends.

**Comment by yuzhva** [comment]
> Drop IE support (Babel config will only target the "last 2 versions" of modern browsers)
https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v300-2020-10-31

Things are changing 🙃

**Comment by CodeCutterUK** [comment]
I think I have a solution - do you want a PR?

**Comment by yuzhva** [comment]
@CodeCutterUK 

That would be awesome, as I'm stuck a bit at work.

**Comment by Trontor** [comment]
> I think I have a solution - do you want a PR?

Any update on this?

**Comment by CodeCutterUK** [comment]
Needs some more testing, but works as well as the previous solution

**Comment by yuzhva** [comment]
**@CodeCutterUK Many thanks for your contribution!**

Your PR #124 has been merged and improved at #125 

The latest version with support of react-leaflet v3.0 available as a candidate release:
```bash
yarn add react-leaflet-markercluster@next # yarn
npm install react-leaflet-markercluster@next # npm
```
Hope that will find some time to improve it.

After some test period will update and republish it as a release package.

Thank you very much 🍻 🍻 🍻

**Comment by barbalex** [comment]
I tested version 3.0.0-rc1 in my app and it seems to work well. Thanks @CodeCutterUK and @yuzhva !

**Comment by agorf** [comment]
> The latest version with support of react-leaflet v3.0 available as a candidate release:
> 
> ```shell
> yarn add react-leaflet-markercluster@next # yarn
> npm install react-leaflet-markercluster@next # npm

@yuzhva Looks like `next` still points to 2.0.0-rc3 https://www.npmjs.com/package/react-leaflet-markercluster

Or I may be missing something.

**Comment by yuzhva** [comment]
@agorf
You have been right. The tags were not updated.

✅ Just updated them.

**Comment by domhaas** [comment]
@yuzhva Since latest react-leaflet ([v3.2.0](https://github.com/PaulLeCam/react-leaflet/releases/tag/v3.2.0)) I'm getting this error:
`No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>`

v3.1.0 is currently working with no issues.

**Comment by sebojanko** [comment]
> @yuzhva Since latest react-leaflet ([v3.2.0](https://github.com/PaulLeCam/react-leaflet/releases/tag/v3.2.0)) I'm getting this error:
> `No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>`
> 
> v3.1.0 is currently working with no issues.

I'm seeing this error on v3.0.4 also.
