### ISSUE TITLE
zoomToBoundsOnClick does not work with disableClusteringAtZoom

### ISSUE THREAD

**Issue by juw177** [yuzhva/react-leaflet-markercluster#128]
disableClusteringAtZoom will expand cluster automatically at a zoom level. If the cluster is expanded by this way and you zoom back out (making it into a cluster again), clicking on the cluster no longer triggers zooms in.

```
<MarkerClusterGroup
        zoomToBoundsOnClick={true} //This is the default
        disableClusteringAtZoom={15}
>
```

This works fine in the leaflet marker cluster demo
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld-maxzoom.388.html

**Comment by yuzhva** [comment]
Unfortunately, I was not able to reproduce the issue in `codesandbox` (added `zoomToBoundsOnClick` and `disableClusteringAtZoom={15}` props, everything was working)

https://codesandbox.io/s/react-leaflet-markercluster-getting-started-9binx

**Comment by juw177** [comment]
Hi @yuzhva , for the sandbox map considering the distance between the markers, I was able to reproduce the issue with disableClusteringAtZoom={5}.

**Comment by juw177** [comment]
Seems to be fine when I also add spiderfyOnMaxZoom=false as per their recommendation
