### ISSUE TITLE
Update leaflet.markercluster dependency

### ISSUE THREAD

**Issue by LoicUV** [YUzhva/react-leaflet-markercluster#13]
Hey !

Could you update to `leaflet.markercluster@1.0.4`, it fixes a breaking bug when you remove a cluster during its animation. cf https://github.com/Leaflet/Leaflet.markercluster/issues/758

Thanks 👌

**Comment by YUzhva** [comment]
@LoicUV ok, I'll do it during that day...

**Comment by YUzhva** [comment]
@LoicUV 

Updated: [release] 1.1.2: Update readme and dependency (#14)
