### ISSUE TITLE
MarkerClusterGroup very low performance with large number of markers

### ISSUE THREAD

**Issue by TiagoPortfolio** [yuzhva/react-leaflet-markercluster#131]
Hello!

In  my environment, I am using:
- "leaflet": "1.7.1"
- "react-leaflet": "2.7.0"
- "react-leaflet-markercluster": "2.0.0"

Tried to load around **1000** markers but the performance is very very low. Did some debugging and it looks like the clusters are being recalculated unnecessarily for some reason.

I found a sandbox to test this from this comment https://github.com/yuzhva/react-leaflet-markercluster/issues/21#issuecomment-610924137:
https://codesandbox.io/s/gallant-leakey-qqupl?file=/src/App.js

Sandbox env:
- "leaflet": "1.7.1"
- "leaflet.markercluster": "1.4.1"
- "react-leaflet": "3.0.2"
- "react-leaflet-markercluster": "3.0.0-rc1"

Does the sandbox need **_leaflet.markercluster_** package? I am not using it on my local env.

**Comment by meliborn** [comment]
Same here, totally useless with 10k markers.

**Comment by Ali762** [comment]
I have just 600 markers. I'm using custom functions for both the marker icon and the cluster icon, (although these just return an svg, or an svg with a number inside, so should be a pretty low performance impact.)

As an example, on a fairly wide zoom on my map, I see three clusters of 80, 450, and 20. One zoom step out, and they all collapse to a single cluster.

Looking in Chrome performance tools, I can see that switching between these two zoom levels is generating hundreds of function calls, creating and destroying individual markers, taking up to 3 seconds to redraw, and the whole page is unresponsive while it does this.

I'd love to figure out how to improve the performance - Even just doing this in the background would help. If it's struggling on my 600 point sample data, there's no way I can scale this to the 20,000 points I need to. Any pointers please?

**Comment by leverglowh** [comment]
To me the codesandbox works just fine, I can move the map and zoom in/out without problems. Is this issue resolved then?

**Comment by TiagoPortfolio** [comment]
> To me the codesandbox works just fine, I can move the map and zoom in/out without problems. Is this issue resolved then?

It is working fine for me as well now. Not sure how the performance was improved since there were any commits...

**Comment by charlieforward9** [comment]
This issue was resolved years ago in #86 has finally been merged into #211. This will be included in the 4.1.0 release very soon!
