### ISSUE TITLE
Typescript error: 'MarkerClusterGroup' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by matheusmb** [yuzhva/react-leaflet-markercluster#133]
Hi, I'm trying to use it with TypeScript but I'm receiving the following error:
```
TypeScript error in /src/components/DashCard/Map/Map.tsx(71,12):
'MarkerClusterGroup' cannot be used as a JSX component.
  Its instance type 'MarkerClusterGroup<any>' is not a valid JSX element.
    Type 'MarkerClusterGroup<any>' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.  TS2786

    69 |             url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    70 |           />
  > 71 |           <MarkerClusterGroup>
       |            ^
    72 |             <Marker position={[-22.8878, -43.2993]}>
    73 |               <Popup>F12</Popup>
    74 |             </Marker>
```

The following packages versions are being used:
```json
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "leaflet": "^1.7.1",
    "react-leaflet": "^3.0.4",
    "react-leaflet-markercluster": "^3.0.0-rc1",
    "typescript": "4.1.2",
```

Anyone has a workaround on this?

**Comment by Silventino** [comment]
Same error here.

**Comment by Silventino** [comment]
As a workaround I've declared a .d.ts file with the following content: 

```
declare module 'react-leaflet-markercluster' {
  // import { MapLayer } from 'react-leaflet';
  import { Component } from 'react';
  export default class MarkerClusterGroup extends Component {}
}
```

If you need to pass props to MarkerClusterGroup, you'll have to change this file too.

**Comment by matheusmb** [comment]
Thanks @Silventino, the workaround worked for me

**Comment by dnehl** [comment]
same error here..

**Comment by k-matti** [comment]
same error here, don't know how to work around

**Comment by dnehl** [comment]
> same error here, don't know how to work around

As a workaround I've wrapped the Markers in a javascript-component (without typescript), where I am using the Cluster. 

`import React from "react";
import MarkerClusterGroup from "react-leaflet-markercluster";
import {MapMarkers} from "./MapMarkers";

const MarkerClustor = ({mapPoints}) => {
    return <MarkerClusterGroup chunkedLoading={true} >
        <MapMarkers mapPoints={mapPoints} />
    </MarkerClusterGroup>
}`

export default MarkerClustor;

**Comment by vitoorgomes** [comment]
thanks a lot @Silventino it worked like a charm! I don't know if someone is still look to maintain this package and the types, but it could be a good PR to open

Again, thanks a lot!

**Comment by DorianMazur** [comment]
I think it should be
```
declare module 'react-leaflet-markercluster' {
    import { Component } from 'react';
    export default class MarkerClusterGroup extends Component<MarkerClusterGroupProps> {}
  }
  ```

**Comment by Silventino** [comment]
Much better!

**Comment by z3v0k** [comment]
same error here!

**Comment by MasterEric** [comment]
Hey all,

The reason for this issue is the fact that this library relies on DefinitelyTyped for its typing, but the DefinitelyTyped definition only provides typing for version 2.0, which relies on `react-leaflet` v2's typing, which is completely different from how the new library works.

The ideal solution would be to convert this library to TypeScript; this would mean type definitions would be provided natively, and would be based on the types for `react-leaflet` v3, which also provides its own native typing.

I am going to work on a PR for this soon.

**Comment by tirli** [comment]
> another user has made [their own library for marker clusters](https://github.com/akursat/react-leaflet-cluster).

Though this library is licensed under GPL, that is not an option for closed-source projects. 

So having proper typings here is still required

**Comment by frf** [comment]
> > another user has made [their own library for marker clusters](https://github.com/akursat/react-leaflet-cluster).
> 
> Though this library is licensed under GPL, that is not an option for closed-source projects.
> 
> So having proper typings here is still required

Tnks @tirli it worked for me this markers clusters very easy

**Comment by piotr-cz** [comment]
I was getting an error *Non-abstract class 'MarkerClusterGroup' does not implement inherited abstract member 'render' from class 'Component<MarkerClusterGroupOptions, {}>'. ts(2515)* so I tweaked @DorianMazur code like this:

```ts
declare module 'react-leaflet-markercluster' {
  import { Component } from 'preact' // Switch to 'react' if you use it
  import { MarkerClusterGroupOptions } from 'leaflet'

  export default abstract class MarkerClusterGroup extends Component<MarkerClusterGroupOptions> {}
}
```

**Comment by fre-ben** [comment]
Thanks @piotr-cz for the snippet. Works fine for me :)

**Comment by codefadeev** [comment]
> I was getting an error _Non-abstract class 'MarkerClusterGroup' does not implement inherited abstract member 'render' from class 'Component<MarkerClusterGroupOptions, {}>'. ts(2515)_ so I tweaked @DorianMazur code like this:
> 
> ```ts
> /**
>  * Type definitions for react-leaflet-markercluster:^3.0.0-rc1
>  * Requires '@types/leaflet.markercluster'
>  */
> declare module 'react-leaflet-markercluster' {
>   import { Component } from 'preact' // Switch to 'react' if you use it
>   import { MarkerClusterGroupOptions } from 'leaflet'
> 
>   export default abstract class MarkerClusterGroup extends Component<MarkerClusterGroupOptions> {}
> }
> ```

Hi.
I did not quite understand. Where did you write it and how did you work with it? I am a beginner and faced this problem.

**Comment by piotr-cz** [comment]
> > I was getting an error _Non-abstract class 'MarkerClusterGroup' does not implement inherited abstract member 'render' from class 'Component<MarkerClusterGroupOptions, {}>'. ts(2515)_ so I tweaked @DorianMazur code like this:
> > ```ts
> > /**
> >  * Type definitions for react-leaflet-markercluster:^3.0.0-rc1
> >  * Requires '@types/leaflet.markercluster'
> >  */
> > declare module 'react-leaflet-markercluster' {
> >   import { Component } from 'preact' // Switch to 'react' if you use it
> >   import { MarkerClusterGroupOptions } from 'leaflet'
> > 
> >   export default abstract class MarkerClusterGroup extends Component<MarkerClusterGroupOptions> {}
> > }
> > ```
> 
> Hi. I did not quite understand. Where did you write it and how did you work with it? I am a beginner and faced this problem.

1. Install library types
   ```console
   npm install --save-dev @types/leaflet.markercluster`
   ```
1. Create `types/react-leaflet-markercluster.d.ts` file with contents above
1. Add type overrides directory in `tsconfig.json`
   ```jsonc
   {
     "compilerOptions": {
       //...
     },
     "include": [
       "src",
       "types"
     ]
   }
   ```

**Comment by codefadeev** [comment]
Thanks @piotr-cz 
And for newbies like me:
1. Create folder `types `with file `react-leaflet-markercluster.d.ts` in the root of the project
2. As in many demo projects on the Internet, I had `react-leaflet-markercluster@2.0.0` installed
This caused the page to not load.
Delete `npm uninstall react-leaflet-markercluster`
Install latest version `npm install react-leaflet-markercluster  `
Right now it is `react-leaflet-markercluster@3.0.0-rc1`
