### ISSUE TITLE
style issue with nextjs

### ISSUE THREAD

**Issue by Yvette14** [yuzhva/react-leaflet-markercluster#134]
I imported css as the document suggested, but the map style was not showing completely.
please help me to solve this problem.
![image](https://user-images.githubusercontent.com/17685849/109098127-afcb5600-775b-11eb-8d14-6a1052ae3c95.png)

**Comment by kennethnwc** [comment]
you may try to import the css in the component
e.g. MyMap.jsx
```jsx
import 'leaflet/dist/leaflet.css';
import 'react-leaflet-markercluster/dist/styles.min.css';
```
