### ISSUE TITLE
Performance issues if MapComponent state is updated

### ISSUE THREAD

**Issue by AndrejGajdos** [yuzhva/react-leaflet-markercluster#135]
I am not sure if this is an issue of react-leaflet-markercluster, react-leaflet, leaflet, or my code. Sorry, if it doesn't belong here.

I have a map with several thousand markers and I am using react-leaflet-markercluster for marker clustering. If I need to update a global state of MapComponent, there is 1-3 seconds delay when this change is reflected.

I created a [codesandox](https://codesandbox.io/s/still-worker-pvuhg) with 5000 markers and you can see there 2 use cases with performance issues:

1.) `MapComponent` is inside [react-reflex](https://www.npmjs.com/package/react-reflex) element, that allows resizing panel and propagates new dimensions (width, height) to MapComponent. If width and height are changed, `mapRef.invalidateSize()` is called to update map dimensions. Resizing is extremely slow.

2.) If user clicks on Marker, global state `selected` is updated. It is a list of clicked marker ids. Map calls `fitBounds` method to focus on clicked marker and also marker icon is changed. There is around 1 second delay.

In my project, if I need to change a MapComponent state, it takes 2-3 seconds in dev mode when changes are reflected and it is just a single rerender of MapComponent and its elements (markers).

I took a look at Chrome performance [profile](https://imgur.com/a/4oh27bW) and it seems most time is spent in internal React methods.

It is possible to fix this by preventing rerendering using `memo`, which is similar to `shouldComponentUpdate`, but it makes whole code base too complicated. `preferCanvas` option doesn't change anything. I am wondering what is a good way to fix these issues.

**Comment by AndrejGajdos** [comment]
Please update README to memoize cluster elements:

const markerComponents = React.useMemo(() => {
    return markers.map((marker) => {
      return (
        <MarkerContainer .../>
      );
    });
  }, [markers, onMarkerClick]);

  return (
    <>
      <MarkerClusterGroup>{markerComponents}</MarkerClusterGroup>
    </>
  );

**Comment by Ali762** [comment]
Plus 100 points sir. I've been struggling for ages with my map. 15000 data points. Custom cluster icons and marker icons. Whenever I dragged the thing around, it was taking up to a full minute to become responsive again. I was trying all sorts to get something useable, and this was the missing piece for me. Everything is buttery smooth again. Thank you!

**Comment by AndrejGajdos** [comment]
@Ali762 yeah if you haven't developed an interactive visualization with thousands of elements in a React project last 2 years, it's hard to figure it out. For this reason I think this should be in Readme, at least as a side note.

**Comment by yuzhva** [comment]
> @Ali762 yeah if you haven't developed an interactive visualization with thousands of elements in a React project last 2 years, it's hard to figure it out. For this reason I think this should be in Readme, at least as a side note.

> For this reason I think this should be in Readme, at least as a side note.

That is an open-source project.
**Contributions are appreciated.**

Originally that was a publicly published pet project.

Unfortunately, I'm overloaded with other projects.

**Comment by AndrejGajdos** [comment]
@yuzhva Yes, of course. Everybody is busy now. I opened PR [here](https://github.com/yuzhva/react-leaflet-markercluster/pull/139).

The thing is that this is my first experience with this library so I thought there could be a reason why optimization with useMemo is not mentioned. I opened this issue first, because I wanted to know creator's opinion on that.
