### ISSUE TITLE
[Q] Does this library supports bulk adding and removing markers

### ISSUE THREAD

**Issue by AndrejGajdos** [yuzhva/react-leaflet-markercluster#138]
I have a question. Is it possible to [bulk adding and removing markers](https://github.com/Leaflet/Leaflet.markercluster#bulk-adding-and-removing-markers) in this library?

**Comment by yuzhva** [comment]
The package does not support bulk adding / removing out of the box.

There is PR with example is avaiable:
https://github.com/yuzhva/react-leaflet-markercluster/pull/86/files#diff-bbaa07b48a4572739e4317e995bb39b840b4161d26f0f21d8b1823c7015b6dc5R6
