### ISSUE TITLE
Always getting an error in @react-leaflet/core at compilation time.

### ISSUE THREAD

**Issue by Harshit-Shah-Ext-Volansys** [yuzhva/react-leaflet-markercluster#150]
ERROR in ./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;

**package.json**

`{
  "name": "react-leaflet-markercluster",
  "version": "3.0.0-rc1",
  "description": "React wrapper of Leaflet.markercluster for react-laeflet",
  "main": "dist/index.js",
  "repository": "git@github.com:YUzhva/react-leaflet-markercluster.git",
  "keywords": [
    "react",
    "leaflet",
    "react-leaflet",
    "markercluster",
    "marker",
    "cluster"
  ],
  "author": "Yevhen Uzhva <yevhen.uzhva@gmail.com>",
  "license": "MIT",
  "private": false,
  "scripts": {
    "dev": "start-storybook -p 8080",
    "lint": "eslint --ext .js ./ --ignore-pattern '/dist/'",
    "build:code": "babel src -d dist && terser ./dist/react-leaflet-markercluster.js -o dist/index.js && rm ./dist/react-leaflet-markercluster.js",
    "build:styles": "node-sass src/styles.scss dist/styles.min.css --output-style compressed",
    "build:source": "yarn build:code && yarn build:styles",
    "build:gh-pages": "build-storybook",
    "deploy:gh-pages": "gh-pages -d storybook-static"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-docs": "^5.3.18",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/react": "^5.3.18",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.4.2",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^2.5.1",
    "gh-pages": "^2.2.0",
    "husky": "^4.2.3",
    "node-sass": "^4.13.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "terser": "^4.6.10"
  },
  "dependencies": {
    "@react-leaflet/core": "^1.0.2",
    "leaflet": "^1.6.0",
    "leaflet.markercluster": "^1.4.1",
    "react-leaflet": "^3.0.0"
  },
  "peerDependencies": {
    "leaflet": "^1.6.0",
    "leaflet.markercluster": "^1.4.1",
    "react-leaflet": "^3.0.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint"
    }
  }
}
`

**Comment by zhiqiyu** [comment]
Hi, I encountered the same problem a few days ago, and I searched around the error message and found this post on Stackoverflow: https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat. Seems that it is not related to this project, but with create-react-app.

**Comment by charlieforward9** [comment]
Please update to the latest version and follow up here if this is still an issue.
