### ISSUE TITLE
Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>

### ISSUE THREAD

**Issue by BowgartField** [YUzhva/react-leaflet-markercluster#156]
Hi huys, 
I'm trying to use this library but i got this problem:
`Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>`
When i 'm trying to create a <MarkerGroup> in my <MapContainer>

I tried the @monsonjeremy's version but it didn't work better.
There is my package.json:
![image](https://user-images.githubusercontent.com/13118844/128769318-25197382-58a0-4e39-a53d-1a51dd7f0c09.png)

Thanks you so much for replies !

**Comment by diggis00** [comment]
Hey, I am getting same issue, did you get any fix?

**Comment by BowgartField** [comment]
> Hey, I am getting same issue, did you get any fix?

Sadly no
