### ISSUE TITLE
lint fails

### ISSUE THREAD

**Issue by frafra** [yuzhva/react-leaflet-markercluster#165]
There are various warning triggered when linting.

It would be a good idea to install husky post-install to avoid such issues in the future.

**Comment by frafra** [comment]
Still a valid suggestion, IMHO.

**Comment by frafra** [comment]
Still relevant.

**Comment by frafra** [comment]
Still relevant... So annoying...

**Comment by frafra** [comment]
Still relevant.

**Comment by frafra** [comment]
Up.

**Comment by frafra** [comment]
Still valid.

**Comment by frafra** [comment]
STILL VALID.

**Comment by charlieforward9** [comment]
@frafra Could you please contribute this if you believe it is still valid? I am unfamiliar with husky but happy to review your contribution to start learning about it.

**Comment by frafra** [comment]
You can just run `npm lint` and check the output :)

**Comment by charlieforward9** [comment]
Thanks for your patience, bump to [4.2.1](https://github.com/yuzhva/react-leaflet-markercluster/releases/tag/v4.2.1)
