### ISSUE TITLE
Blinker popup

### ISSUE THREAD

**Issue by sm2017** [yuzhva/react-leaflet-markercluster#167]
`MarkerClusterGroup` and `Popup` is not working well together, when popup is open and we have a re-render the popup is blinking

In the following code I have two marker, you can see the marker with `MarkerClusterGroup` parent has blink but another has not,
I think you must pass a stable `key` to markers

```js
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import "./styles.css";
import MarkerClusterGroup from "react-leaflet-markercluster";
import { useEffect, useState } from "react";

export default function App() {
  const [position, setPosition] = useState([51.505, -0.09]);
  const [position2, setPosition2] = useState([51.506, -0.08]);

  useEffect(() => {
    setInterval(() => {
      setPosition((position) => {
        const [lat, lon] = position;

        return [lat + 0.0001, lon + 0.0001];
      });

      setPosition2((position) => {
        const [lat, lon] = position;

        return [lat + 0.0001, lon + 0.0001];
      });
    }, 1000);
  }, []);

  return (
    <MapContainer center={position} zoom={13}>
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <MarkerClusterGroup>
        <Marker position={position}>
          <Popup>Blinker popup</Popup>
        </Marker>
      </MarkerClusterGroup>

      <Marker position={position2}>
        <Popup>No bug</Popup>
      </Marker>
    </MapContainer>
  );
}

```

**Comment by sm2017** [comment]
@yuzhva can you please take a look?

**Comment by ErnestBrandi** [comment]
Hi, usually please provide a sandbox so people can dive in.
Also yes, try to pass an arbitrary key : `<MarkerClusterGroup key={Date.now()}>`

**Comment by sm2017** [comment]
[![Edit condescending-jepsen-xdw83](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-jepsen-xdw83?fontsize=14&hidenavigation=1&theme=dark)

I have some issue  with marker icon in code sandbox ignore it just see the Blinker bug

I am not talking about `MarkerClusterGroup` key , I just think that the marker is blinking because it is re-rendering always an the is a but in react-leaflet-markercluster

**Comment by butters16** [comment]
I just ran in to the same problem today. Before looking here, I proved it wasn't a problem in leaflet (https://plnkr.co/edit/1kznV2ddI13h8akg) or react-leaflet (https://codesandbox.io/s/react-leaflet-forked-ywr6i7). The sandbox example here is pretty perfect, @sm2017. Well done!

Can this issue please be reopened?

**Comment by sm2017** [comment]
Unfortunately it marked as wontfix

**Comment by butters16** [comment]
@yuzhva, the bot closed this but it seems valid and has pretty good steps to reproduce. Can you edit labels and reopen?

@sm2017, did you ever find a workaround?
