### ISSUE TITLE
getting cluster location

### ISSUE THREAD

**Issue by Morette** [yuzhva/react-leaflet-markercluster#168]
Hello,
I need to get cluster location but can't figure out how.

I know that on events like *onClick* and *iconCreationFunction* I can pass the cluster as parameter, but can't find and event to be used for when the cluster is being created.

**Comment by mattbbc** [comment]
```
<MarkerClusterGroup
  ...
  onClick={(e) => console.log(e.layer.getLatLng())}
/>
```
