### ISSUE TITLE
Invalid Hook Call issue

### ISSUE THREAD

**Issue by roecc** [yuzhva/react-leaflet-markercluster#190]
In a fresh project with nothing but newest version of react, leaflet etc. installed, the app breaks as soon as i try to implement MarkerClusterGroup throwing me a "Invalid Hook Call" issue. I might be doing something wrong, but i can't find the problem.

**Comment by barbalex** [comment]
duplicate of https://github.com/yuzhva/react-leaflet-markercluster/issues/187
