### ISSUE TITLE
When "react-leaflet-markercluster" will support  react-leaflet 4?

### ISSUE THREAD

**Issue by iamrraj** [yuzhva/react-leaflet-markercluster#196]
I am trying to react-leaflet-markercluster  on react-leaflet but i could not because they error like this `Invalid hook call. Hooks can only be called inside of the body of a function component`  because i have multiple marker that overlapping on each other.

**Comment by jaballogian** [comment]
hi @iamrraj 

I think your issue is the same as this issue https://github.com/yuzhva/react-leaflet-markercluster/issues/187
Currently, I use this marker cluster library https://github.com/yuzhva/react-leaflet-markercluster/issues/187#issuecomment-1175025801 for react-leaflet v4 and react v18

**Comment by iamrraj** [comment]
Thanks ,Exactly it helped me to solve my problem,
