### ISSUE TITLE
Use custom React Component for marker, cluster, popup

### ISSUE THREAD

**Issue by DoubleYo** [yuzhva/react-leaflet-markercluster#21]
Hello,
nice work on this plugin.
Now you can use HTML string or element in popup. This is possible to use a custom React Component because with more than 1'000 marker react can't handle the charge.

https://github.com/OpenGov/react-leaflet-cluster-layer use a `clusterComponent` which is realy nice. But it missing a lot of fonctionnality (animation, spiderify...) and the positioning is not as good.

Regards, Yoann.

**Comment by YUzhva** [comment]
As I understood there is lugs when you have more then 1000 markers?

Are you using Marker from react-leaflet or passing them as array through `markers=""` prop?

**Comment by DoubleYo** [comment]
Yes, the markers needs to have custom div icon. 
And clusters needs custom react component (like pie chart).

**Comment by YUzhva** [comment]
@DoubleYo 

> Are you using Marker from react-leaflet or passing them as an array through markers="" prop?

Could you write a small example on how are you passing markers to the MarkerClusterGroup, so I could reproduce lugs?

**Comment by Eric24** [comment]
+1 for dynamic custom cluster symbol (probably by letting the developer provide their own component, since the range of possibilities is large). One possible use-case: When all the markers being collapsed into the cluster symbol are the "same", then a circle with a count is fine, but when there are different marker "types" it would often be important to have the cluster symbol reflect this; @DoubleYo suggested a pie chart, which is a good idea, but even being able to dynamically set the style/color of the cluster symbol might be sufficient in some cases.

**Comment by YUzhva** [comment]
@Eric24 

> One possible use-case: When all the markers being collapsed into the cluster symbol are the "same", then a circle with a count is fine, but when there are different marker "types" it would often be important to have the cluster symbol reflect this; 

How I'm currently deal with that:

```javascript
const markerclusterOptions = {
  iconCreateFunction: (cluster) => {
    const clusterClass = getClusterClass(cluster.getAllChildMarkers());
    return L.divIcon({
      html: cluster.getChildCount(),
      className: `custom-cluster-classname cluster-${clusterClass}`,
      iconSize: L.point(40, 40, true),
    });
  },
  showCoverageOnHover: false,
  maxClusterRadius: 45,
  spiderfyDistanceMultiplier: 2,
};

// ...
<MarkerClusterGroup
  markers={this.props.markers}
  options={markerclusterOptions}
/>

function getClusterClass(markersList) {
  const combinedMarker = false;

  // Disabling rule, because we need to break loop at specific condition
  for (const marker of markersList) { // eslint-disable-line no-restricted-syntax
    if (marker.options.someMarkerCustomOption) {
      combinedMarker = true;
      break;
    }
  }

  return combinedMarker ? 'combined' : 'single';
};
```

So the className for each cluster will be: `custom-cluster-classname` and depending on markers inside this cluster (`someMarkerCustomOption` marker option) that you could pass with options prop, cluster will additionally have`cluster-combined` or `cluster-single` class name.

**Comment by jbccollins** [comment]
ReactDomServer has a function called renderToStaticMarkup which I've used successfully to render pie charts.

```
    return L.divIcon({
      html: ReactDOMServer.renderToStaticMarkup(
        <div>
          <span className='cluster-count'>{childCount}</span>
          <PieChart data={data}/>
        </div>
      ),
      className: `pie-cluster ${klass}`, 
      iconSize: new L.Point(size, size)
    })
```

**Comment by vasiledraghita** [comment]
I don't know if my problem relates to this, but if I sent array of markers within props it does not show any cluster nor markers. Only if I put the array as children for <MarkerClusterGroup> component. Any idea why?

**Comment by jbccollins** [comment]
@vasiledraghita  https://github.com/YUzhva/react-leaflet-markercluster#api
Passing in markers as props is deprecated anyway.

**Comment by vasiledraghita** [comment]
@jbccollins It works if I sent the markers as childrens, but if I have more than 500 markers the performance is very low. I cannot move the map, only zoom-in or zoom-out si working. And I thought that if I send via markers props I will perform better...

**Comment by YUzhva** [comment]
@vasiledraghita 

Markers as a **props** are deprecated, so @jbccollins was right (=

Please send them as children like that:
```
import { Maker } from 'react-leaflet';
import MarkerClusterGroup from 'react-letaflet-markercluster';

// ...

<MarkerClusterGroup>
  <Marker position={[49.8397, 24.0297]} />
  <Marker position={[52.2297, 21.0122]} />
  <Marker position={[51.5074, -0.0901]} />
</MarkerClusterGroup>
```

That is more the react way than sending them to props.

**Comment by vasiledraghita** [comment]
@YUzhva I am using that way, but with a custom icon for markers. And I've tested with over 500 markers and it freezes. I cannot move the map, only zoom-in or zoom-out is working.

`
import {Map, Marker, TileLayer} from 'react-leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import L from 'leaflet';
import MapMarker from '../../../assets/images/MapMarker.svg';

const MAX_ZOOM = 21;
const DATA_TOOLTIP_ID = 'leaflet-map-tooltip';
// ...
render() {
    const markerIcon = L.divIcon({
      className: 'div-marker-icon',
      html: `<img src="${MapMarker}" data-tooltip-id="${DATA_TOOLTIP_ID}">`,
      iconSize:    [25, 41],
      iconAnchor:  [12, 41],
    });

    const markers = this.props.points.map((item, index) => {
      return <Marker
        key={item.sessionKey}
        position={[item.lat, item.lng]}
        icon={markerIcon}
      />
    });

    return <div className='leaflet-map-panel'>
      {this.renderTooltip()}
      <Map
        center={this.state.center}
        zoom={this.state.zoom}
        maxZoom={MAX_ZOOM}
        onViewportChange={this.onViewportChange}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"/>
        <MarkerClusterGroup removeOutsideVisibleBounds={true}>
          {markers}
        </MarkerClusterGroup>
      </Map>
    </div>;
  }`

**Comment by jbccollins** [comment]
@vasiledraghita Well without a fiddle or codepen that's gonna be difficult to debug. I found that leaflet-markercluster will recluster sometimes when I did not expect it to. To get around this I extended react-leaflet-markercluster like so:

```javascript
// This is really dumb but for whatever reason MarkerClusterGroup will recluster even when the key does not change.
// To get around this horrible inefficiency we re-mount the cluster when it actually needs to change and ignore
// every other change.
class CustomMarkerClusterGroup extends MarkerClusterGroup {
  shouldComponentUpdate() {
    return false;
  }
}
```

Works for me with 5000 markers just fine.

**Comment by vasiledraghita** [comment]
Tanks @jbccollins. It worked, but not extending MarkerClusterGroup because React throws some error for some reason, so I use it like this in another file.
`import React, {Component} from 'react';
import MarkerClusterGroup from 'react-leaflet-markercluster';

export default class CustomMarkerClusterGroup extends Component {
  shouldComponentUpdate() {
    return false;
  }

  render() {
    return <MarkerClusterGroup {...this.props}/>
  }
}`

**Comment by jbccollins** [comment]
@vasiledraghita Ah. I see why it doesn't work. `react-leaflet-markercluster` was recently updated to work with `react-leaflet` v2.0.0. This line: https://github.com/YUzhva/react-leaflet-markercluster/blob/master/src/react-leaflet-markercluster.js#L34 breaks extending `MarkerClusterGroup`. I raised an issue with it two weeks ago on the `react-leaflet` repo: https://github.com/PaulLeCam/react-leaflet/issues/506. If the maintainer of that repository does not agree that all components should be extendable then I'm seriously considering publishing a fork that fixes that.

**Comment by yuzhva** [comment]
the `v2.0.0` has been released...

Here is the working CodeSandbox:
https://codesandbox.io/s/react-leaflet-markercluster-getting-started-9binx

**Comment by TiagoPortfolio** [comment]
It keeps breaking with a large number of markers...

I tried using this sandbox https://codesandbox.io/s/react-leaflet-markercluster-getting-started-9binx with **500** clusters and can't even move the map
