### ISSUE TITLE
Can't use with Meteor

### ISSUE THREAD

**Issue by Kolyasya** [YUzhva/react-leaflet-markercluster#23]
Hello, I develop Meteor + React + Leaflet map and just tried to use your package.
Can't run it even with temporary default setup, have an error in console:

```
meteor.js?hash=27829e9…:930 Exception from Tracker recompute function:
meteor.js?hash=27829e9…:932 undefined
```
Without markercluster plugin map works fine, markers and popups are working too.

I have a simple setup:
Location is reactive.

```
const markers = [
      {lat: 47.2, lng: 39.7},
      {lat: 47.21, lng: 39.71},
      {lat: 47.22, lng: 39.72},
    ];

    return (
      <div className="map-container">
        <Map
          center={[this.state.location.lat, this.state.location.lng]}
          zoom={13}
          style={{ height: '100%' }}
          ref="map"
        >
          <TileLayer
            url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"
            attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
          />

         <MarkerClusterGroup
           markers={markers}
           wrapperOptions={{enableDefaultStyle: true}}
         />

        </Map>
      </div>
    );
```

Do you have any ideas what should I check and fix to make it work?

**Comment by YUzhva** [comment]
I think issue appears because of importing .css styles inside the component.

In v1.1.6 there will be deprecation warning about `wrapperOptions` param, so I'm going to remove it in v1.2.0.

**Comment by YUzhva** [comment]
If you ar using npm/yarn, you could try go to: `node_modules/react-leaflet-markercluster/dist/`, open `react-leaflet-markercluster.js` and comment next line:
```javascript
// require('./style.css');
```

Then import it (by default it takes .min version, but you need to import changed not minimized script):
```javascript
import MarkerClusterGroup from 'react-leaflet-markercluster/dist/react-leaflet-markercluster';
```

If that issue will disappear, so I will need to write deprecation warning for using `wrapperOptions` and stop to using that prop and style import from v1.2.0

**Comment by YUzhva** [comment]
P.S: I decided to combine all the issues that touch to that refactoring into issue #48
