### ISSUE TITLE
How to use GeoJSON with this Library 

### ISSUE THREAD

**Issue by lalithnarayan** [YUzhva/react-leaflet-markercluster#24]
Hi ,

I have been trying to using this library to add cluster on Leaflet layers using GeoJSON but I'm unable to do it. Can you please share an example.

Thanks in Advance

**Comment by estarguars113** [comment]
In my case I'm using superagent to fetch the data from my REST service, returning a geojson. I¿m reading the features and building the markers array in the format specified, I'm not sure if it's the best approach, but right now it's working 

`if(endpoint){
      request
        .get(endpoint)
        .end(function(error, response){
          if (error) return console.error(error);
          var geojson = response.body;
          var features = geojson['features'];
          var markers = [];

          for(var index in features){
             var feature = features[index];
             //validate it contains the geo info
             if(feature && feature['geometry']){
               var coordinates = feature['geometry']['coordinates'];
               var point = {
                 lat: coordinates[1],
                 lng: coordinates[0]
               }
               markers.push(point);
             }
          }
          this.setState({
            geojson: geojson,
            features: features,
            markers: markers

          });
        }.bind(this));
    }`

**Comment by YUzhva** [comment]
@lalithnarayan Did you try to conver Markercluster to getJSON like:

```javascript
 <MarkerClusterGroup
    markers={markers}
    wrapperOptions={{enableDefaultStyle: true}}
    ref={(cluster) => console.log('cluster', cluster.leafletElement.toGeoJSON())}
  />
```
