### ISSUE TITLE
How to select individual marker?

### ISSUE THREAD

**Issue by tusharkhatiwada** [YUzhva/react-leaflet-markercluster#26]
Hi,
I've a group of markers with and they all have unique ID. I've implemented **Markercluster** using the following code: 

```
<MarkerClusterGroup
  ref={markerClusterGroup => {
	this.markerClusterGroup = markerClusterGroup;
	}}
	markers={vehicleMarkers}
	options={{
	showCoverageOnHover: false,
	spiderfyDistanceMultiplier: 2
	}}
	wrapperOptions={{ enableDefaultStyle: true }}
	markerOptions={{ icon: OnlineMarker }}
/>
```
The markers are as follow:

```
[{
  lat: 27.3214,
  lng: 81.4312,
  deviceId: 1A1,
  tooltip: this.renderTooltip("vehicle no")
},
........
]
```

How can I select specific marker with their **deviceId**?

When not using **Markercluster**, I could use **ref** on the **Marker** like: `ref = {(1A1) => {this.1A1 = 1A1}}`. The `1A1` would be dynamic. 

Is it possible to assign ref to all the markers or is there anything I could do to make it work?

Thanks

**Comment by YUzhva** [comment]
Rendered marker at Leaflet Map doesn't have all info like `id` or whatever custom info that you will provide in `vehicleMarkers` list.

If you need to get all that info about marker that was clicked, you could do something like this:
```javascript
onMarkerClick={(marker) => this.selectMarkerByCoordinates(marker.getLatLng())}

selectMarkerByCoordinates(coordinates) {
  vehicleMarkers.find((marker) => (marker.lat === coordinates.lat) && (marker.lng === coordinates.lng))
}
```

**Comment by YUzhva** [comment]
Another way is to add marker id to its options (you need move id to options object):

```javascript
[{
  lat: 27.3214,
  lng: 81.4312,
  deviceId: 1A1,
  tooltip: this.renderTooltip("vehicle no"),
  options: { myCustomId:  '1A1' },
},
........
]

onMarkerClick={(marker) => console.log(marker.options.myCustomId)}
```

**Comment by YUzhva** [comment]
@tusharkhatiwada Could you please close that issue if there is everything ok and the question was resolved?

🚀 Thanks

**Comment by akuji1993** [comment]
Thanks for this @YUzhva wasn't aware you could append your own options to the options attribute. Maybe include that somewhere in your tutorial. Otherwise very happy with your lib!
