### ISSUE TITLE
How to use custom React component for marker icon?

### ISSUE THREAD

**Issue by prajwal78** [YUzhva/react-leaflet-markercluster#29]
I need a help for using custom React component for marker's icon and clustering the custom markers.

**Comment by YUzhva** [comment]
For setting custom marker icon, please check [DEMO example](https://yuzhva.github.io/react-leaflet-markercluster/#marker-options).

For setting custom cluster icon, please use `iconCreateFunction` option:
```javascript
const markerclusterOptions = {
  iconCreateFunction: (cluster) => (
    L.divIcon({ html: '<b>' + cluster.getChildCount() + '</b>' });
  ),
};
```

**Comment by jaballogian** [comment]
There is an issue with `iconCreateFunction` prop combined with `ReactDOMServer.renderToString()` function here https://stackoverflow.com/questions/71522257/useeffect-hook-isnt-triggered-inside-reactdomserver-rendertostring
