### ISSUE TITLE
Update markers and refresh map

### ISSUE THREAD

**Issue by maxbax** [YUzhva/react-leaflet-markercluster#30]
How can I upgrade MarkerClusterGroup after updating markers as a react component state? Initially state.markers are empty, but after a few seconds I add some points on it, but nothing happens ...

<MarkerClusterGroup
markers = {this.state.markers}
wrapperOptions = {{enableDefaultStyle: true}} />

Thanks 
Max

**Comment by Clafouti** [comment]
How are you updating your state ?
Can you provide some code that currently doesn't work ?

I'm using this library like this : 
```jsx
<MarkerClusterGroup
  markers={this.state.markersForClusters}
  wrapperOptions={{enableDefaultStyle: true}}
  onMarkerClick={this.onMarkerClusterClick}
/>
```

And I don't have any problem.

**Comment by maxbax** [comment]
Thanks for the answer. I have to load markers in more times. This is my code:
```

**Comment by Clafouti** [comment]
I'm not sure what is causing this, I tried your code in codesandbox (https://codesandbox.io/s/J6ynwlOq9) and it seems to work fine (the state is updated).

Is your state updated in your case ?

**Comment by maxbax** [comment]
Yes, the state work well, but the MarkerClusterGroup doesn't refresh the points, so I can't see the new ones

**Comment by YUzhva** [comment]
@maxbax 

MarkerClusterGroup rerendering markers when:
```
componentWillReceiveProps(nextProps) {
  if (nextProps.markers.length && !isArraysEqual(this.props.markers, nextProps.markers)) {
    // ...
```

Could you, please try to add `this.forceUpdate();` for each tick, to see if there issue with rerendering of parent component?
```
this.timerID = setTimeout(() => {
        this.tick();
        this.forceUpdate();
      },
      1000
    );
```

**Comment by maxbax** [comment]
Your're right. Thanks a lot, now it works.
