### ISSUE TITLE
npm install fails because of missing release (1.1.6) published on npmjs.com

### ISSUE THREAD

**Issue by Zombaya** [YUzhva/react-leaflet-markercluster#33]
The latest version published on npmjs.com is 1.1.6, but this version is missing on your repo here.  This results in a failing install for this module.

For now I could fix this by changing the dependency on your project from `>1.1.5` to `1.1.5` but this way I won't be getting any updates when you release new versions.

Is it possible to remove the latest release from npmjs.com or actually release a version 1.1.6?

**Comment by YUzhva** [comment]
@Zombaya 

I pushed the latest tag to GitHub repo, `v1.1.6` is tagged.

Did it resolved issue?

**Comment by Zombaya** [comment]
Yes, this has resolved the issue.  

Thanks for the quick response! :+1:
