### ISSUE TITLE
className added to map container on mount not removed on unmount

### ISSUE THREAD

**Issue by lightsinthesky** [YUzhva/react-leaflet-markercluster#34]
The classes marker-cluster-styled and marker-cluster-animated are added to the map container on mount but not removed on unmount - this causes issues when attempting to use the marker clusters dynamically as the classname string gets continually larger as clusters are added and removed.

**Comment by YUzhva** [comment]
Fixed at: [release] 1.1.7: Minor fixes, deprecation API warnings and refactoring (#47)
