### ISSUE TITLE
How to best handle multiple cluster layers at once?

### ISSUE THREAD

**Issue by Eric24** [YUzhva/react-leaflet-markercluster#37]
I'm trying to figure out the best way to handle this scenario: I have multiple cluster layers, each representing a particular kind of object (kept on separate layers so the user can view or hide them as they desire). Each individual cluster layer works as expected, clustering as you zoom out, but the result is multiple cluster markers on top of each other.

I don't think there is such a thing as a cluster of cluster layers, but short of that, is there any suitable approach?

**Comment by toomuchdata** [comment]
@Eric24 it's been a while since the query but just in case it still helps...
`allMarkers = ds.features.map((feature) => {
              return(
                {
                  lat: feature.geometry.coordinates[1],
                  lng: feature.geometry.coordinates[0],
                  tooltip: feature.properties.NAME,
                  options: {
                    icon: customIcons[key],
                    title: key,
                    feature: feature,
                  }
                }
              );
            });
            returnMarkerLayers.push(
              <MarkerClusterGroup
                key={key}
                markers={allMarkers}
                options={markerClusterOptions}
                wrapperOptions={{enableDefaultStyle: true}}
                onMarkerClick={(marker) => this.addPopup(marker.options.title, marker.options.feature)}
              />
            );`
where allMarkers is an array of all markers for a "kind of object", and returnMarkerLayers contains all <MarkerClusterGroup />.  You can loop through the above for each "kind of object".
