### ISSUE TITLE
Map not rerendering on getting new options

### ISSUE THREAD

**Issue by akuji1993** [YUzhva/react-leaflet-markercluster#38]
I have an issue with updating the clusters options and the map not registering. I have a switch to return different options objects with different iconCreateFunctions so I can show different informations on the cluster icon. But while my state is getting updatet correctly and the MarkerClusterGroup correctly receives new options, it's not doing anything actually. 

This is my code: 

````
<Map className={classNames('markercluster-map', s.map)} center={viewPosition} maxZoom={18} zoom={6} minZoom={6}>
            <TileLayer
              url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
              attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>'
            />
            <MarkerClusterGroup
              onMarkerClick={this.handleMarkerClick}
              markers={markers}
              ref={(clusterGroup) => { this.clusterGroup = clusterGroup; }}
              options={this.getMarkerClusterOptions(this.props.clusterType)}
              wrapperOptions={{enableDefaultStyle:true}}/>
</Map>
````

I'm aware of https://github.com/YUzhva/react-leaflet-markercluster/issues/30 but since my markers are not updating, just the way I want to show them, it doesn't apply here.

**Comment by YUzhva** [comment]
Could you please write an example how are you updating the markers at `markers` array?

**Comment by akuji1993** [comment]
I'm not updating the markers at all. They're just the same array of points every render() call. I only alter the object that gets returned by `this.getMarkerClusterOptions(this.props.clusterType)`

**Comment by akuji1993** [comment]
If it helps somehow, this is the whole class: 

`
import React from 'react';
import {Map, Marker, Popup, TileLayer} from 'react-leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import s from './SelectMap.scss';
import {connect} from 'react-redux';
import {ClusterIcon, getMarkerIcon} from '../../ui';
import Selection from '../Selection/Selection';
import classNames from 'classnames';
import {Message} from '../../../util';
import MapClusterController from './MapClusterController';
import {setSelectedMarkets, addMessageWithTimeout} from '../../../actions/actions';
import clusterTypes from './clusterTypes';

const mapStateToProps = (state) => {
  return ({
    markets: state.markets,
    selectedMarkets: state.selectedMarkets,
    clusterType: state.clusterType
  });
};

const viewPosition = [50.94, 6.9];
class SelectMap extends React.Component {

  constructor() {
    super();
    this.handleMarkerClick = this.handleMarkerClick.bind(this);
    this.toggleMarket = this.toggleMarket.bind(this);
  }

  handleMarkerClick(marker) {
    let markerID = marker.options.id;
    let market = this.props.markets.find(m => m.wwident === markerID);
    this.toggleMarket(market);
  }

  toggleMarket(market) {
    let selectedMarket = this.props.selectedMarkets.find(m => m.wwident == market.wwident);

    if (this.props.selectedMarkets.length > 1) {
      // show message that as of now, only two markets can be compared
      this.props.dispatch(
        addMessageWithTimeout(
          new Message('Im Moment können nur 2 Märkte miteinander verglichen werden.', 'info')
        )
      );

    } else {
      if (!!selectedMarket) {
        // Filter market out, removes it from the selected markets
        this.props.dispatch(setSelectedMarkets(this.props.selectedMarkets.filter(m => m.wwident !== market.wwident)));
      } else {
        // Add market to the selected markets array
        this.props.dispatch(setSelectedMarkets([...this.props.selectedMarkets, market]));
      }
    }
  }

  getMarkerClusterOptions(clusterType) {
    var markerClusterOptions = {};
    console.log('returning clusterType ', clusterType);

    switch (clusterType) {
      case clusterTypes.rating:
        console.log('rating');
        markerClusterOptions = {
          id: 1,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;

      case clusterTypes.amount:
        console.log('amount');
        markerClusterOptions = {
          id: 2,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;

      case clusterTypes.revenue:
        console.log('revenue');
        markerClusterOptions = {
          id: 3,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;
    }

    return markerClusterOptions;
  }

  render() {

    let markers = this.props.markets.map(market => {
      // const tt = L.tooltip({direction: 'top'}).setContent(`${market.n+ame}, ${market.str}, ${market.stadt}`);
      return {id: market.wwident, lat: market.lat, lng: market.long, options: {id: market.wwident, rev: market.rev, icon: getMarkerIcon(market.sge)}};
    });

    return (
      <div className={s.selectMap}>
        <MapClusterController
          clusterType={this.props.clusterType}
          dispatch={this.props.dispatch}/>
        <div className={s.mapContainer}>

          {!!this.props.markets &&
          <Map className={classNames('markercluster-map', s.map)} center={viewPosition} maxZoom={18} zoom={6} minZoom={6}>
            <TileLayer
              url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
              attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>'
            />
            <MarkerClusterGroup
              onMarkerClick={this.handleMarkerClick}
              markers={markers}
              ref={(clusterGroup) => { this.clusterGroup = clusterGroup; }}
              options={this.getMarkerClusterOptions(this.props.clusterType)}
              wrapperOptions={{enableDefaultStyle:true}}/>
          </Map>}
        </div>
        <div className={s.selectContainer}>
          <Selection onMarketSelect={this.toggleMarket}/>
        </div>
      </div>
    );
  }
}

export default connect(mapStateToProps)(SelectMap);
`

**Comment by akuji1993** [comment]
If it helps somehow, this is the whole class: 

`````
import React from 'react';
import {Map, Marker, Popup, TileLayer} from 'react-leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import s from './SelectMap.scss';
import {connect} from 'react-redux';
import {ClusterIcon, getMarkerIcon} from '../../ui';
import Selection from '../Selection/Selection';
import classNames from 'classnames';
import {Message} from '../../../util';
import MapClusterController from './MapClusterController';
import {setSelectedMarkets, addMessageWithTimeout} from '../../../actions/actions';
import clusterTypes from './clusterTypes';

const mapStateToProps = (state) => {
  return ({
    markets: state.markets,
    selectedMarkets: state.selectedMarkets,
    clusterType: state.clusterType
  });
};

const viewPosition = [50.94, 6.9];
class SelectMap extends React.Component {

  constructor() {
    super();
    this.handleMarkerClick = this.handleMarkerClick.bind(this);
    this.toggleMarket = this.toggleMarket.bind(this);
  }

  handleMarkerClick(marker) {
    let markerID = marker.options.id;
    let market = this.props.markets.find(m => m.wwident === markerID);
    this.toggleMarket(market);
  }

  toggleMarket(market) {
    let selectedMarket = this.props.selectedMarkets.find(m => m.wwident == market.wwident);

    if (this.props.selectedMarkets.length > 1) {
      // show message that as of now, only two markets can be compared
      this.props.dispatch(
        addMessageWithTimeout(
          new Message('Im Moment können nur 2 Märkte miteinander verglichen werden.', 'info')
        )
      );

    } else {
      if (!!selectedMarket) {
        // Filter market out, removes it from the selected markets
        this.props.dispatch(setSelectedMarkets(this.props.selectedMarkets.filter(m => m.wwident !== market.wwident)));
      } else {
        // Add market to the selected markets array
        this.props.dispatch(setSelectedMarkets([...this.props.selectedMarkets, market]));
      }
    }
  }

  getMarkerClusterOptions(clusterType) {
    var markerClusterOptions = {};
    console.log('returning clusterType ', clusterType);

    switch (clusterType) {
      case clusterTypes.rating:
        console.log('rating');
        markerClusterOptions = {
          id: 1,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;

      case clusterTypes.amount:
        console.log('amount');
        markerClusterOptions = {
          id: 2,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;

      case clusterTypes.revenue:
        console.log('revenue');
        markerClusterOptions = {
          id: 3,
          iconCreateFunction: (cluster) => {
            var value = cluster.getChildCount(),
              outMin = 25, // minimale Pixelgröße
              outMax = 100, // maximale Pixelgröße
              inMin = 2, // minimaler Wert in value
              inMax = 2500; // maximaler Wert in value

            var val = outMin + ((outMax - outMin) / (inMax - inMin)) * (value - inMin);
            val = Math.min(val, 100);
            var lh = val / outMin * 2;

            return new ClusterIcon(val, lh, value);
          }
        };
        break;
    }

    return markerClusterOptions;
  }

  render() {

    let markers = this.props.markets.map(market => {
      // const tt = L.tooltip({direction: 'top'}).setContent(`${market.n+ame}, ${market.str}, ${market.stadt}`);
      return {id: market.wwident, lat: market.lat, lng: market.long, options: {id: market.wwident, rev: market.rev, icon: getMarkerIcon(market.sge)}};
    });

    return (
      <div className={s.selectMap}>
        <MapClusterController
          clusterType={this.props.clusterType}
          dispatch={this.props.dispatch}/>
        <div className={s.mapContainer}>

          {!!this.props.markets &&
          <Map className={classNames('markercluster-map', s.map)} center={viewPosition} maxZoom={18} zoom={6} minZoom={6}>
            <TileLayer
              url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
              attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>'
            />
            <MarkerClusterGroup
              onMarkerClick={this.handleMarkerClick}
              markers={markers}
              ref={(clusterGroup) => { this.clusterGroup = clusterGroup; }}
              options={this.getMarkerClusterOptions(this.props.clusterType)}
              wrapperOptions={{enableDefaultStyle:true}}/>
          </Map>}
        </div>
        <div className={s.selectContainer}>
          <Selection onMarketSelect={this.toggleMarket}/>
        </div>
      </div>
    );
  }
}

export default connect(mapStateToProps)(SelectMap);

```````

**Comment by akuji1993** [comment]
Also right now, all three cases in getMarkerClusterOptions are the same, but if I changed stuff in them, nothing happens to the cluster. I changed the size of the ClusterIcon (more specifially the range of the size) and they stay exactly the same size.

**Comment by YUzhva** [comment]
You should update markers through setState() or by updating `<SelectMap markets={} />` property.

Because React rerendering component in two cases:
- when the component state was updated through setState()
- when component receiving new properties.

**Comment by akuji1993** [comment]
I don't need to update the markers. All I want to update is the options object that is given to the MarkerClusterGroup, so the clusters show up in different styles (in this case, different information on them).

**Comment by akuji1993** [comment]
I got it working with a hack: Since I need three different options objects in MarkerClusterGroup I made three MarkerClusterGroup div's that only one is rendered of, depending on which of the three options I need. Then I give that MarkerClusterGroup the options object I need, and voilá working. The map doesn't rerender, just the cluster with all the markers.
