### ISSUE TITLE
Issue with build (scss vs css)

### ISSUE THREAD

**Issue by thisissami** [YUzhva/react-leaflet-markercluster#40]
Hi - I'm addressing two things here:

1) There's some incongruences between how you handle the markers prop & how the original markercluster library handles the markers array. I've created a fix in my own local branch of this repository, and would like to push it here & create a pull request. Can you give me permission to do that? 

2) Separate from the fixes that I've created: when running `npm run build:source`, the generated `.js` files in `dist` folder require `./style.scss` while `gulp` outputs `./style.css`. I had to manually change the require to `.css` for the build to work.

**Comment by YUzhva** [comment]
@thisissami Hey hi, thank you for your contributing.

You could create a pull request from your forked repo directly to my repo like that:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by thisissami** [comment]
@YUzhva thanks! gonna do this now. :)

**Comment by thisissami** [comment]
Ok - I've created the pull request (see #41). The `scss` vs `css` issue still remains. If the solution is "manually change the require lines in the `dist` folder after it's built", it would be good to add that to the `README.md` so that people know that's the case.

**Comment by YUzhva** [comment]
The steps with renaming style files extension where describe at [Contributing section](https://github.com/YUzhva/react-leaflet-markercluster#contributing)

The enhancement of the plugin planned for the `v1.2.0` where we are going to drop support of `wrapperOptions` API.
[Deprecation warnings already release at v1.1.7](https://github.com/YUzhva/react-leaflet-markercluster/releases/tag/v1.1.7)

P.S: I decided to combine all the issues that touch to that refactoring into issue #48
