### ISSUE TITLE
package.json main is pointing to a minified version that doesnt exist

### ISSUE THREAD

**Issue by jbritton** [YUzhva/react-leaflet-markercluster#43]
The main property of the package json contains this entry but the release only contains the non-minified version ```dist/react-leaflet-markercluster.js``` causing the ES6 import to fail.
```json
{
...
 "main": "dist/react-leaflet-markercluster.min.js",
...
}
```

**Comment by joeyparis** [comment]
Try running `yarn add leaflet.markercluster` or `npm i --save leaflet.markercluster`

**Comment by YUzhva** [comment]
Improved at: [release] 1.1.7: Minor fixes, deprecation API warnings and refactoring (#47)

P.S: added the note about peerDependency at README.md
