### ISSUE TITLE
How to pass user-defined props to markers?

### ISSUE THREAD

**Issue by vietnugent** [YUzhva/react-leaflet-markercluster#45]
First off thank you for porting the cluster plugin to react land. 

According this [PR](https://github.com/YUzhva/react-leaflet-markercluster/pull/4) I'm under the impression that it's possible to pass custom props to markers and retrieve them in `onMarkerClick(marker)` event.

I produce an array of markers as per the example with one additional `index` property in hope of passing it along to some UI event in `onMarkerClick` handler.  Unfortunately the `marker` object in the callback looks like a leaflet object minus the custom property.
```
render() {
const markers = geojsonData.map(
   (feature, index) => {    
      return {
         lat: ...,
         lng: ...,
        options: ...,
         index: index  // my custom property
      }
   }
)

return (   <MarkerClusterGroup
                        markers={markers}
                        onMarkerClick={onMarkerClickHandler}
         />)

...
const onMakerClickHandler = (marker) => {
   console.log(marker.index);  // index is undefined
}
```

**Comment by vietnugent** [comment]
You can actually pass custom data to each marker via the `options` property (see leaflet L.Marker) though it's not very well-documented in Leaflet.  I'm documenting the solution here for those who may come across this issue.

```javascript
render() {
  const markers = geojsonData.map(
     (feature, index) => {    
        return {
           lat: ...,
           lng: ...,
           options: { 
               myDataIndex: index,  /* this will be available in onMakerClick() callback */ 
               icon: myIcon, /* other L.Marker options */
            },
       }
    }
 );
...
```

**Comment by athenawisdoms** [comment]
@vietnugent I'm encountering the same issue... How can we pass an object into the `options` property of the `<Marker />` React component?

I am using TypeScript (and new to it) and it appears that the `options` property is not defined for the `Marker` component. For example, we get the missing `options` property error when we have

```jsx
<MarkerClusterGroup iconCreateFunction={createCustomClusterIcon}>
{
    markers.map((marker, index) => (
        <Marker 
            position={[marker.lat, marker.lon]} 
            key={index}
            options={{ count: marker.count }}   // <===== property does not appear to be defined?
        />
    ))
}
</MarkerClusterGroup>
```
