### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by satori-jstoffan** [YUzhva/react-leaflet-markercluster#46]
Would it be possible to update the `peerDependencies` in `package.json` to support React 16? The react-leaflet library [recently did the same](https://github.com/PaulLeCam/react-leaflet/commit/ae4793de0848dcf53e8b51af8fb0d0c56b55d2d3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45).

**Comment by YUzhva** [comment]
Improved at: [release] 1.1.7: Minor fixes, deprecation API warnings and refactoring (#47)
