### ISSUE TITLE
Custom data associated with the child marker

### ISSUE THREAD

**Issue by sommcz** [YUzhva/react-leaflet-markercluster#50]
Hi,
is there any way how to store custom data into marker (for use in callbacks - eg. iconCreateFunction after calling cluster.getAllChildMarkers()).

Normally i could store new property into created marker object or use L.Util.stamp to get unique ID of marker element.

Feature request:
- add new optional property to element in markers array customData
- store this property into marker object after creation with L.marker, is customData prop is set

thank you

**Comment by sommcz** [comment]
Workarouond: this approach now works with .options property, which is less clean, but working too.

**Comment by YUzhva** [comment]
Isn't it related to the: https://github.com/YUzhva/react-leaflet-markercluster/issues/26#issuecomment-313917719
