### ISSUE TITLE
Fetarure request: Support for other Cluster Events

### ISSUE THREAD

**Issue by sommcz** [YUzhva/react-leaflet-markercluster#51]
Hi,

component binds only onClusterClick event, but original leaflet plugin supports more of them:
https://github.com/Leaflet/Leaflet.markercluster#events

Is possible to add them to react component too?

**Comment by YUzhva** [comment]
Related to the issue #49 

Will add it in next version.

**Comment by YUzhva** [comment]
This issue was resolved in beta `v2.0.0-rc1` release.

There are available all leaflet [map Interaction events](https://leafletjs.com/reference-1.3.0.html#map-interaction-events) like dblclick/mouseup/mousedown etc.

Just v2.x of that plugin requires react-leaflet@^2.0.0.
