### ISSUE TITLE
Clarify onMarkerClick arguments / best practice

### ISSUE THREAD

**Issue by bluerface** [YUzhva/react-leaflet-markercluster#56]
I guess I really have two related requests 
1) Clarify in the documentation what the argument passed to onMarkerClick is. I have looked at it in the console so I can find individual properties for it, but Im not sure if it is a custom class for this library, from the markercluster library, or from leaflet...?

2) How are people using this eventHandler? My use case is to display info for the location which was clicked, which means the knowledge of what has been clicked needs to be passed through, and this must be the case for most people using this function.  

Currently I am passing through a custom locationId property to the marker 'options' object, which is then available as <onMarkerClick-arg-1-some-kind-of-marker-object>.options.<my-custom-locationId-prop>, but this feels unstable. 

Is there an undocumented onClick property for the marker object that could be bound with the location's id?  Is there / could there be a user-data property that would be passed through? Could it be documented that custom marker.options properties will be passed through (thereby reassuring us that it is a stable api)

**Comment by YUzhva** [comment]
> 1) what the argument passed to onMarkerClick is
You should pass there function that will be invoked when user will click on marker
> 2) How are people using this eventHandler?
https://yuzhva.github.io/react-leaflet-markercluster/#event-listeners
```javascript
invokeSpesificFunction() {
  console.log(marker, marker.getLatLng());
  // TODO:
}
render(
// ...
    <MarkerClusterGroup
      markers={markers}
      onMarkerClick={(marker) => invokeSpesificFunction(marker)}
    />
// ...
)
```

**Comment by bluerface** [comment]
I dont think you read my questions at all...

1) was asking what argument is given to the onMarkerClick handler, not what I should pass as the onMarkerClick prop.  You show it in the above code as 'marker' but is it the leaflet marker instance? 

2) I know how to use react, my question is how do you identify which of your business objects the marker object corresponds to?  You can compare the latlng, and that seems to be the way folks are doing it elsewhere, but that is not always going to be unique? Much preferable to be able to attach an id (which the code currently does, but using undocumented and therefore unstable features)
