### ISSUE TITLE
no ref on Marker

### ISSUE THREAD

**Issue by reactvi1** [YUzhva/react-leaflet-markercluster#59]
Hi,
On most react components and once in Marker react leaflet, I was able to direct the picture once it was loaded. Unfurtantely, whenever I try to use the ref props with Marker, I get an undefined call.
Can anyone know what's the problem?

**Comment by YUzhva** [comment]
For accessing `ref` property - you should use `Marker` from `react-leaflet`:

```javascript
<MarkerClusterGroup>
      <Marker
        position={[49.8397, 24.0297]}
        ref={(marker) => {
          console.log("marker", marker);
        }}
      />
      <Marker position={[52.2297, 21.0122]} />
      <Marker position={[51.5074, -0.0901]} />
    </MarkerClusterGroup>
```

**Comment by reactvi1** [comment]
that what I've done.
it seems that neither the function never called or that marker is undefined.

**Comment by mkotar** [comment]
Hi - the same issue - as @reactvi1 said - the code @YUzhva showed does nothing. In my case nothing is printed in console.

**Comment by YUzhva** [comment]
@mkotar which version of `react-leaflet-markercluster` are you using?

**Comment by mkotar** [comment]
@YUzhva: 1.1.7

**Comment by YUzhva** [comment]
Are you exporting markers like:
```javascript
import Marker from "react-leaflet"?
```
