### ISSUE TITLE
Custom cluster coloring

### ISSUE THREAD

**Issue by ayanez17** [YUzhva/react-leaflet-markercluster#61]
Is there a way to color the cluster based on the average of an options value ?
Meaning that if the cluster contains 6 points and each point has an option called point_value the color would be based on the average of those points?

```
const markers = [
  { position: [49.8397, 24.0297], options: { point_value: 10 } },
  { position: [50.4501, 30.5234], options: { point_value: 0 } },
  { position: [52.2297, 21.0122], , options: { point_value: 10 } },
  { position: [50.0647, 19.9450], options: { point_value: 0 } },
  { position: [48.9226, 24.7111],, options: { point_value: 10 }},
  { position: [48.7164, 21.2611], options: { point_value: 0 } },
];
```

Color pseudocode.
```
average_value_ for_cluster =( 10+0+10+0+10+0)/6
if (average_value_ for_cluster>4){
color = 'green'
} else if(average_value_ for_cluster<4){
color='orange'
}else if(average_value_ for_cluster===0){
color='red'
}
```

Therefore this cluster would  be 'green'

**Comment by aghalarp** [comment]
Late response, but for anyone else having trouble with this, it can be done by providing a function via the 'iconCreateFunction' option, where you can do all your necessary calculations before ultimately returning a Leaflet DivIcon. You'll have to create your own custom CSS rules, which you can then pass to the DivIcon (along with any HTML you might want to display with your cluster icon).

The following is pretty much all you need to figure this out:
https://yuzhva.github.io/react-leaflet-markercluster/#markercluster-options
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers
https://leafletjs.com/reference-1.3.0.html#divicon

**Comment by aqueiros** [comment]
The links provided by @aghalarp were very helpful. Thank you!
I would just add that since I simply wanted to flip the red-green colours, but keep the default style, this link was also useful: 
https://github.com/Leaflet/Leaflet.markercluster/blob/master/dist/MarkerCluster.Default.css 

This is the code that worked for me:
```
const createClusterCustomIcon = function(cluster) {
  const count = cluster.getChildCount();
  let colorClass = '';
  if (count <= 10) {
    colorClass = 'marker-cluster-large';
  } else if (count <= 50) {
    colorClass = 'marker-cluster-medium';
  } else colorClass = 'marker-cluster-small';
  return L.divIcon({
    html: `<div><span>${count}</span></div>`,
    className: `leaflet-marker-icon marker-cluster ${colorClass} leaflet-zoom-animated leaflet-interactive`,
    iconSize: L.point(40, 40, true),
  });
};
```
I then tweaked it to receive all of the markers + zoomLevel and decide which color to use based on that.
