### ISSUE TITLE
Git merge conflict markers checked into master

### ISSUE THREAD

**Issue by rm-hull** [YUzhva/react-leaflet-markercluster#63]
See:

https://github.com/YUzhva/react-leaflet-markercluster/blob/e9d9ff1ed6314d83373ef3d1045c9eeca6727b7b/dist/react-leaflet-markercluster.min.js#L1-L5

**Comment by rm-hull** [comment]
Nudge @YUzhva  ☝️

**Comment by YUzhva** [comment]
Fixed at: [release] 1.1.8: Remove deprecated-styles. Use react-leaflet context for markers. (#62)
