### ISSUE TITLE
Issue showing custom React Component over default cluster logo

### ISSUE THREAD

**Issue by mrinmoydas3011** [YUzhva/react-leaflet-markercluster#64]
Hi,

I want to show a React component whenever the markers are clustered instead of the default green circle that is shown. How to achieve this?

**Comment by YUzhva** [comment]
You could user `iconCreateFunction ` as a part of [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers) API.

Please, check that example:
https://yuzhva.github.io/react-leaflet-markercluster/#markercluster-options

**Comment by mrinmoydas3011** [comment]
Hi,

I am using it for the this for the first time and it is very unclear to me. Actually, I want to show a 'rechart' instead of the cluster default green icon. Please help!

**Comment by jaballogian** [comment]
There is an issue with `iconCreateFunction` prop combined with `ReactDOMServer.renderToString()` function here https://stackoverflow.com/questions/71522257/useeffect-hook-isnt-triggered-inside-reactdomserver-rendertostring
