### ISSUE TITLE
Property `iconCreateFunction` not passed on to Leaflet Element?

### ISSUE THREAD

**Issue by ldegen** [YUzhva/react-leaflet-markercluster#74]
Hi @YUzhva, 
nice work, thanks a lot!

I am passing a  custom `iconCreateFunction` to the `MarkerClusterGroup` component, (like described in the README), but it seems to be ignored.

I tried to understand what was going on and stumbled upon this code line:

https://github.com/YUzhva/react-leaflet-markercluster/blob/master/src/react-leaflet-markercluster.js#L13

Shouldn't that have been `prop.startsWith(…)` rather than `includes`? 
The string `iconCreateFunction` includes 'on' two times, but afaics it should not be treated as an event
handler in this context, right?

I see what happens if I change this and will report back here.

**Comment by YUzhva** [comment]
@ldegen Thank you for notice and your contribution! (=
Already fixed that issue in `2.0.0-rc3`.

At first, remove `-rc2` and then install the latest candidate release:
```
yarn add react-leaflet-markercluster@next # yarn
npm install react-leaflet-markercluster@next # npm
```

**Comment by YUzhva** [comment]
Will do it in the release version, when README/CHANGELOG and demo-app will be updated too :wink:

**Comment by ldegen** [comment]
FYI: I just checked out rc3, at least in Chrome it works now.
