### ISSUE TITLE
Markers inside a MarkerClusterGroup are fully re-rendered on the actual DOM when host Map re-renders

### ISSUE THREAD

**Issue by cherouvim** [YUzhva/react-leaflet-markercluster#78]
Deps used:
```
    "leaflet": "1.3.4",
    "leaflet.markercluster": "1.3.0",
    "react": "16.4.2",
    "react-dom": "16.4.2",
    "react-leaflet": "1.9.1",
    "react-leaflet-markercluster": "1.1.8",
```

Reproduce:
- code: https://codesandbox.io/s/1j1wo6pv3
- demo: https://1j1wo6pv3.codesandbox.io/
- details: Open up the demo and see the 4 cat markers. The upper 2 are orphan, directly hosted on the `Map`, and the lower 2 are wrapped inside a `MarkerClusterGroup`. I've setup a timer which will force an `App` re-render every 3 seconds by updating the `App` state. Open up dev tools and inspect the cat markers. You'll notice that the upper 2 cat markers are not touched/altered when the `App` render takes place, but the lower 2, which are wrapped in the `MarkerClusterGroup`, always get fully re-rendered.

Nothing has changed on the `MarkerClusterGroup` and the `Marker`s within, so this behavior is problematic in many ways.

**Comment by aalpgiray** [comment]
Anything on this one?
