### ISSUE TITLE
Spiderfy won't work from code

### ISSUE THREAD

**Issue by RominaMartin** [YUzhva/react-leaflet-markercluster#79]
I have a table with a list of points represented in map with cluster. When I click in a row from table I want the map to be centered on the cluster and spiderfy it. 

I access the cluster by obtaining the layers on the map and run 
```cluster.spiderfy();```

It doesn't spidefy it, however if I log `cluster` and from chrome developer I run the exact same line as above: `cluster.spiderfy();` and in this way it works! 

I'm not sure what to look at now, maybe this has happened to someone else?

**Comment by Falkyouall** [comment]
Was there any progression on it? 
IO manage to fire the spiderfy() function on the parent, but all what happens is that the cluster icon gets some opacity, but no spiderfying is happening :(
