### ISSUE TITLE
Toggle spiderfy/unspiderfy by cluster icon click

### ISSUE THREAD

**Issue by kolyasya** [YUzhva/react-leaflet-markercluster#81]
Hello, I use this simple function to spiderfy cluster by mouse click:

```
onClusterClick={ e => {
  e.spiderfy();
}}
```

For now I ended up by adding a wrapper component for each cluster and using its state like so:

```
this.state = {
  spiderfy: false
};
```

```
onClusterClick={ e => {
  const { spiderfy } = this.state;
  if (spiderfy)
    this.setState({ spiderfy: false }, () => e.unspiderfy());
  else {
    this.setState({ spiderfy: true }, () => e.spiderfy());
  }
}}
```

What is a proper way to detect if cluster is already spiderfied and unspiderfy in back on a next click?

**Comment by YUzhva** [comment]
Not sure if it is the same question as here:
https://github.com/Leaflet/Leaflet.markercluster/issues/716

Didn't has such a case.

**Comment by kolyasya** [comment]
@YUzhva yes, it seems like the same.

I was looking for a variable holding status state but haven't find one
