### ISSUE TITLE
React Leaflet v2 is not supported

### ISSUE THREAD

**Issue by gudvinga** [YUzhva/react-leaflet-markercluster#83]
React Leaflet v2 is not supported.
Will react-leaflet-markercluster be updated to support of react-leaflet v2?

**Comment by gudvinga** [comment]
Thank you, it works!

**Comment by webdobe** [comment]
Doesn't look like much has happened in past year.  Any chances 2.x is going to be tagged?

**Comment by YUzhva** [comment]
@webdobe oh men - I'm overloaded.

I'm thinking to drop support of v1.x and focus just on v2.x support in the nearest future.
