### ISSUE TITLE
Pass user defined data to `iconCreateFunction`

### ISSUE THREAD

**Issue by bonjefir** [YUzhva/react-leaflet-markercluster#84]
I want to customize marker groups with a criteria which comes from app logic. So I pass bellow function as `iconCreateFunction` prop to `MarkerClusterGroup`. `markerTypes` has information about location and its group-marker style(its class name in css file).
```
const createClusterCustomIcon = (markerTypes) => {
	console.log('markerTypes(closure) ', markerTypes)
	return (cluster) => {
		console.log('markerTypes ', markerTypes)
		let type = 'normal'; // this must change to markerTypes[idx] according to app logic
		return L.divIcon({
			html: `<span class="marker-cluster">${cluster.getChildCount()}</span>`,
			className: `marker-cluster-${type}`,
			iconSize: L.point(30, 30, true),
		});
	}
}

```

Also I used it in the following code.

```
<MarkerClusterGroup
	showCoverageOnHover={false}
	iconCreateFunction={createClusterCustomIcon(markerTypes)}
>
	{renderLocations(locations)}
</MarkerClusterGroup>

```
*The problem is here:* In the first time which above code rendered `locations` and `markerTypes` are empty arrays(since they take value in `componentDidMount` and they are empty in constructor). So `MarkerClusterGroup` takes a `createClusterCustomIcon` which has `markerTypes` with value `[]`. After running `componentDidMount`, `createClusterCustomIcon` change and updates its  `markerTypes` but this does not apply to `MarkerClusterGroup`.

On the other hand, `console.log('markerTypes(closure) ', markerTypes)` runs two times. First time it logs `markerTypes []` and second one `markerTypes [has values as expected]`. But `console.log('markerTypes ', markerTypes)` logs `markerTypes []` every time it render markers...

```
"react": "^16.5.2",
"leaflet": "^1.3.1",
"leaflet.markercluster": "^1.4.1",
"react-leaflet": "^1.9.1",
"react-leaflet-markercluster": "^1.1.8",
```

**Comment by bonjefir** [comment]
Please somebody tell me what is the status of this issue. If problem statement is not clear or it is too long please tell me.

**Comment by DennisWeini** [comment]
You want to pass Data from a Marker to the MarkerClusterGroup?
I make it this way:
` <Marker
                  key={index}
                  position={[station.lat, station.lng]}
                  icon={this.getStateMarker(station.name, load)}
                  calc={load}
                  companyLocation={station.location}
                  name={station.name}
                  onClick={(e) => this.onCircleClick(e, station)}
                >`

I just give the Markers new options, and when you call getAllChildMarkers(), the Markers will have the values: "calc", "name" and "companyLocation" which I added to the options

**Comment by athenawisdoms** [comment]
@DennisWeini How can we pass these new options to `Marker` if we are using TypeScript? TypeScript will give an error message about the new options not being defined...

**Comment by TheUniqueMathemagician** [comment]
@athenawisdoms  You can use regular react data attributes like 
`
<Marker data-name="Hello World"/>
`. It would then be available in options["data-name"]
