### ISSUE TITLE
TypeError: Cannot read property '_layerAdd' of null

### ISSUE THREAD

**Issue by gilneto8** [yuzhva/react-leaflet-markercluster#85]
Hi,

First of all, thanks for what seems to be an intuitive library for marker clustering, it was exactly what I was looking for. Unfortunately I'm having some problems getting it to work with react-leaflet.

Below is the code that's giving me the error:
```javascript
import React from 'react';
import { Map, Marker, Popup, TileLayer } from 'react-leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import styles from '../styles/SiteMap.scss';

class SiteMap extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      hasLocation: false,
      position: {
        lat: 41.3,
        lng: -7.69
      },
      zoom: 13
    }

    this.mapRef = React.createRef();
  }

  handleClick = (e) => {
    console.log(e);
  }

  render() {
    const { position, zoom } = this.state;

    return (
      <Map
        className={`markercluster-map ${styles.map}`}
        center={position}
        zoom={zoom}
        maxZoom={20}
        onClick={this.handleClick}
        ref={this.mapRef}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          map={this.mapRef}
        />
        <MarkerClusterGroup>
          <Marker position={position}>
            <Popup>A pretty CSS3 popup.<br />Easily customizable.</Popup>
          </Marker>
          <Marker position={{ lat: 41.2, lng: -7 }}>
            <Popup>A pretty CSS3 popup.<br />Easily customizable.</Popup>
          </Marker>
        </MarkerClusterGroup>
      </Map>
    );
  }
}

export default SiteMap;
```
Please note that I was just fooling around with the library to get to see the clustering in action. And I am able to see it if I start the server directly, but our scripts run a few tests using jest and enzyme beforehand, to make sure everything is ok. And this is where the problem appears:
`TypeError: Cannot read property '_layerAdd' of null`

I came to the conclusion that this problem happens whenever I have the `<MarkerClusterGroup>` wrapper around my markers. If I delete it, the tests run perfectly and no issue appears.

Can you help me with this? Any tip on getting this to work? Below are the versions I'm using for the required libraries:
```
    "react": "^16.6.1",
    "prop-types": "^15.6.2",
    "react-leaflet": "^1.7.8",
    "leaflet.markercluster": "^1.4.1",
    "react-leaflet-markercluster": "^1.1.8",
```

Thanks in advance!
Gil

**Comment by forman** [comment]
One issue here may be that support for react 16.x has only been added in react-leaflet 2.x, see https://github.com/PaulLeCam/react-leaflet/releases/tag/v2.0.0.

**Comment by gilneto8** [comment]
@forman thanks for the answer, I've now updated react-leaflet to version 2.1.2, thus updating the package.json.

Unfortunately, it seems I'm still facing some issues. Right now, the error that is shown is as follows:

```
Uncaught TypeError: Super expression must either be null or a function, not object
```

Be aware that I haven't changed the code implemented, only updated the library.

**Comment by forman** [comment]
@gilneto8 I've seen that message too. It goes away if you use the "next" tag when installing `react-leaflet-markercluster`:

    yarn add react-leaflet-markercluster@next

**Comment by vikram-gsu** [comment]
@gilneto8 and @forman  - Still seeing the initial error(Cannot read property _layerAdd of null) currently.

Here's my basic env:
"react": "^16.8.4",
"react-dom": "^16.8.4",
"react-leaflet": "^2.2.1",
"react-leaflet-sidebarv2": "^0.6.0",

Were y'all able to resolve this?

**Comment by yuzhva** [comment]
> @gilneto8 and @forman - Still seeing the initial error(Cannot read property _layerAdd of null) currently.
> 
> Here's my basic env:
> "react": "^16.8.4",
> "react-dom": "^16.8.4",
> "react-leaflet": "^2.2.1",
> "react-leaflet-sidebarv2": "^0.6.0",
> 
> Were y'all able to resolve this?

`leaflet` and `leaflet.markercluster` dependencies are missing:
```javascript
yarn add react-leaflet-markercluster leaflet.markercluster leaflet react-leaflet
```

P.S: here is the working CodeSandbox:
https://codesandbox.io/s/react-leaflet-markercluster-getting-started-9binx

Also, the DEMO app has been updated.
