### ISSUE TITLE
Specify zIndex

### ISSUE THREAD

**Issue by brucem1976** [YUzhva/react-leaflet-markercluster#87]
Is there a way to specify the zIndex of the clusters? In react-leaflet I am able to do this:
```
<Marker
        position=...
        zIndexOffset={CUSTOM_VALUE}
        ...
```

**Comment by YUzhva** [comment]
Did not found that Option at [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster#options) documentation.

**Comment by brucem1976** [comment]
It is mentioned here through clusterPane: [https://github.com/Leaflet/Leaflet.markercluster/issues/817](url) - do you think it's possible in react-leaflet-markercluster too?

**Comment by brucem1976** [comment]
Thanks I tried that but it didn’t work - do you think MarkerClusterGroup preserves that zIndex for its children?

**Comment by brucem1976** [comment]
I did some more reading on this - <Marker> elements themselves can have zIndexOffset values - how is the zIndex of MarkerClusterGroup determined?

**Comment by brucem1976** [comment]
Got this working: I added a Pane to the main map:
`<Pane name="custom-page" style={{ zIndex: 700 }} />
`
and then referenced in the cluster:
```
<MarkerClusterGroup
      iconCreateFunction={createClusterCustomIcon}
      maxClusterRadius={20}
      clusterPane="custom-page"
    >
```
