### ISSUE TITLE
[Q] How to access list of children in marker group?

### ISSUE THREAD

**Issue by bonjefir** [YUzhva/react-leaflet-markercluster#90]
I want to display cluster group icon with respect to some information of its children. So I need to access points info(e.g, location, id and status) in `createClusterCustomIcon`. I can access to count of points which a group contained with `cluster.getChildCount()` function but I could not find any way to access list of its children.

Something like [this](https://github.com/adammertel/Leaflet.MarkerCluster.List) example, each marker cluster group has list of its points.

**Comment by YUzhva** [comment]
Hey hi, @bonjefir 

Here is a link for official doc: [Other clusters methods](https://github.com/Leaflet/Leaflet.markercluster#other-clusters-methods)

> I need to access points info
If you need to get marker props, probably you are looking for `getAllChildMarkers` method.

```javascript
const createClusterCustomIcon = function (cluster) {
  const clusterChildMarkers = cluster.getAllChildMarkers(); // list of all markers
  return L.divIcon({
    html: `<span>${cluster.getChildCount()}</span>`,
    className: 'marker-cluster-custom',
    iconSize: L.point(40, 40, true),
  });
};

<MarkerClusterGroup
  showCoverageOnHover={false}
  spiderfyDistanceMultiplier={2}
  iconCreateFunction={createClusterCustomIcon}
>

  <Marker position={[49.8397, 24.0297]} />
  <Marker position={[50.4501, 30.5234]} />
</MarkerClusterGroup>
```

**Comment by bonjefir** [comment]
Thanks @YUzhva 

Again 

> I want to display cluster group icon with respect to some information of its children.

 Also I need to use `refreshClusters` method which it is documented [here](https://github.com/Leaflet/Leaflet.markercluster#refreshing-the-clusters-icon), but I could not find it in `react-leaflet`. Moreover, it seems `iconCreateFunction` saves its value, so if it changes after data updated with ajax call it does not update.

As an example if `stations` changes and fills with ajax call, we could not access to new data in `iconCreateFunction`...
```
const createClusterCustomIcon = function(stations) {
	return function(cluster) {
		let type = 'normal'; // stations[idx]
		return L.divIcon({
			html: `<span class="marker-cluster">${cluster.getChildCount()}</span>`,
			className: `marker-cluster-${type}`,
			iconSize: L.point(30, 30, true),
		});
	}
}
```

**Comment by spostad7** [comment]
same question here @yuzhva, 
I want to get all markers lat lng in on cluster. how can I get that?
