### ISSUE TITLE
onMarkerClick not working in example 

### ISSUE THREAD

**Issue by fas3r** [YUzhva/react-leaflet-markercluster#91]
Hello @YUzhva , 

in the [example](https://yuzhva.github.io/react-leaflet-markercluster/#event-listeners) the markers are not rendering.

And if using `onMarkerClick` like the following it's not working either : 

```

        <MarkerClusterGroup
          onMarkerClick={marker => console.log("test")}
        >

          <Marker position={[49.8397, 24.0297]}>
            <Tooltip>
              <span>my tooltip text 1</span>
            </Tooltip>
          </Marker>

          <Marker position={[50.4501, 30.5234]} />
          <Marker position={[52.2297, 21.0122]} />
          <Marker position={[50.0647, 19.9450]} />
          <Marker position={[48.9226, 24.7111]} />
          <Marker position={[48.7164, 21.2611]} />
        </MarkerClusterGroup>
```

Thanks.

**Comment by owlyowl** [comment]
It would appear if you click on the map layer then on the marker or cluster it works it seems like some kind of focus issue. Did someone ever figure this one out?

**Comment by owlyowl** [comment]
It would appear in the source code they need to return true; after binding the "on" events as otherwise the event doesn't propagate. Adding that appears to fix it just fine,

**Comment by YUzhva** [comment]
✅ 
The demo has been replaced with the StoryBook doc.
