### ISSUE TITLE
Single marker fails to get rendered if it is not in or close to a cluster

### ISSUE THREAD

**Issue by oifun** [YUzhva/react-leaflet-markercluster#93]
@YUzhva 

In my map application, I am fetching the marker positions from a JSON file and want to cluster the markers which are located nearby. Using the MarkerClusterGroup, the clustered markers render successfully as required. However, if there is a single marker which is either not part of a cluster or close to a cluster, it does not render on the map. This is reproducible when passing the markers as an array to markers prop as well as when defining the Markers component directly in MarkerClusterGroup (as shown in example).

In the code snippet below, the first 6 markers are rendered as a cluster since they are located close. However, the last marker (position={[42.2793, -71.4162]}) is not displayed at all since it in not part of any of the clusters. What is the best way to fix this?

```javascript

  render() {
    const mapCenter = [this.center.lat, this.center.lng];
    return (
      <LeafletMap 
        center={mapCenter} 
        zoom={this.center.zoom}
        maxZoom={10}
        minZoom={2.5}
        maxBounds={[[-85,-180],[85,180]]}
        maxBoundsViscosity={0.1}
        bounceAtZoomLimits={true}     
        easeLinearity={0.35} 
        >
        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
        />

        <MarkerClusterGroup
              showCoverageOnHover={false}
              spiderfyDistanceMultiplier={2}
              animate={true}
              zoomToBoundsOnClick={true}
              spiderfyOnMaxZoom={false}
              maxClusterRadius={60}
            >
            <Marker position={[50.0647, 19.9450]} />
            <Marker position={[48.9226, 24.7111]} />
            <Marker position={[48.7164, 21.2611]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[42.2793, -71.4162]} />
         </MarkerClusterGroup>
      </LeafletMap>
    );
  }

```
    "leaflet": "^1.5.1",
    "leaflet.markercluster": "^1.4.1",
    "react-leaflet": "1.9.1",
    "react-leaflet-markercluster": "^1.1.8",

```


```

**Comment by YUzhva** [comment]
1. Did you try to display a single marker without clustering them?

2. Did you included styles, into your project?
you need to imclude both, leaflet:
https://leafletjs.com/examples/quick-start/

and leaflet.markercluster:
````
@import '~react-leaflet-markercluster/dist/styles.min.css'; // sass
@import url('~react-leaflet-markercluster/dist/styles.min.css'); // css

require('react-leaflet-markercluster/dist/styles.min.css'); // inside .js file
```

**Comment by oifun** [comment]
Hello @YUzhva 

Regarding your feedback:

1. Single marker outside of a MarkerClusterGroup works. However, a single marker inside the MarkerClusterGroup does not get displayed.

2. The required styles for Leaflet and react-leaflet-markercluster are imported in the project. I've added the following to the index.html page within the head section (as suggested here [https://www.npmjs.com/package/react-leaflet-markercluster#getting-started](url):

``` 
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
    integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
    crossorigin=""/>
<!--Make sure you put this AFTER Leaflet's CSS-->
<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
    integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
    crossorigin=""></script>
<link rel="stylesheet" href="https://unpkg.com/react-leaflet-markercluster/dist/styles.min.css" />
```
I've also tried importing the react-leaflet-markercluster/dist/styles.min.css in the css and .js files.

**Comment by oifun** [comment]
@YUzhva - Any update on this? I'd appreciate your feedback. Please let me know if a codepen/fiddle environment would help.

**Comment by a5l3** [comment]
Same issue on my end. 
After clicking a cluster the icons seem to disappear. 
<img width="767" alt="single-render" src="https://user-images.githubusercontent.com/43312868/62596690-ee848b80-b8eb-11e9-84f4-39b589d44171.png">
<img width="188" alt="cluster-render" src="https://user-images.githubusercontent.com/43312868/62596693-f0e6e580-b8eb-11e9-859e-982dca2f7c93.png">

**Comment by a5l3** [comment]
Found a solution! 

See - https://github.com/PaulLeCam/react-leaflet/issues/453#issuecomment-410450387
``` javascript 
import L from 'leaflet';

delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});
```

**Comment by oifun** [comment]
@a5l3 Thanks for your feedback. But I already have that included in my file and am still having the issue.

**Comment by oifun** [comment]
> Found a solution!
> 
> See - [PaulLeCam/react-leaflet#453 (comment)](https://github.com/PaulLeCam/react-leaflet/issues/453#issuecomment-410450387)
> 
> ```js
> import L from 'leaflet';
> 
> delete L.Icon.Default.prototype._getIconUrl;
> 
> L.Icon.Default.mergeOptions({
>     iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
>     iconUrl: require('leaflet/dist/images/marker-icon.png'),
>     shadowUrl: require('leaflet/dist/images/marker-shadow.png')
> });
> ```

@a5l3 Thanks for your feedback. But I already have that included in my file and am still having the issue.

**Comment by a5l3** [comment]
``` javascript 
import 'leaflet/dist/leaflet.css';
import 'react-leaflet-markercluster/dist/styles.min.css';

import {
    Map,
    TileLayer,
    Marker, 
    LayersControl,
    LayerGroup,
  } from 'react-leaflet';



delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});

            <LayersControl position="bottomleft">
              <LayersControl.Overlay name="Markers" checked>
                <LayerGroup>
        <MarkerClusterGroup
              showCoverageOnHover={false}
              spiderfyDistanceMultiplier={2}
              animate={true}
              zoomToBoundsOnClick={true}
              spiderfyOnMaxZoom={false}
              maxClusterRadius={60}
            >
            <Marker position={[50.0647, 19.9450]} />
            <Marker position={[48.9226, 24.7111]} />
            <Marker position={[48.7164, 21.2611]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[51.5, -0.09]} />
            <Marker position={[42.2793, -71.4162]} />
         </MarkerClusterGroup>

                </LayerGroup>
                  
              </LayersControl.Overlay>
            </LayersControl>
```

try wrapping MarkerClusterGroup with Layergroup and or LayersControl

**Comment by oifun** [comment]
@YUzhva 

Thanks for getting back. It turns out that the problem was with one of the LeafletMap props. Using a non-integer value for minZoom somehow was affecting the markercluster. Updating the value to an integer fixed the clustering issue.
