### ISSUE TITLE
Get all Child Markers

### ISSUE THREAD

**Issue by bilemedimkq** [YUzhva/react-leaflet-markercluster#94]
Hello,

I am using the cluster structure in my project and i want to know one thing:

How can i get the list of the markers grouped inside a cluster?

`
constructor(props) {
    this.markerCluster=React.createRef();
    setInterval(() => {
            console.log(this.markerCluster.current.getAllChildMarkers()); // <=== This not work
     }, 500);
}

render() {
   return(
      ..map
          <MarkerClusterGroup ref={this.markerCluster}>
              <Marker ..values.. />
              <Marker ..values.. />
              <Marker ..values.. />
              <Marker ..values.. />
          </MarkerClusterGroup>
      map..
   )
}

`

**Comment by YUzhva** [comment]
@bilemedimkq 

There is an example written in the documentation:
[https://yuzhva.github.io/react-leaflet-markercluster/#event-listeners--heading](https://yuzhva.github.io/react-leaflet-markercluster/#event-listeners--heading)

```
<MarkerClusterGroup
  onClusterClick={(cluster) => console.log(cluster, cluster.getAllChildMarkers())}
>
  <Marker />
  <Marker />
  <Marker />
</MarkerClusterGroup>
```
