### ISSUE TITLE
Importing MarkerClusterGroup results in error

### ISSUE THREAD

**Issue by jakobpack** [yuzhva/react-leaflet-markercluster#95]
Receiving following error:
`TypeError: (0, _reactLeaflet.withLeaflet) is not a function. (In '(0, _reactLeaflet.withLeaflet)(MarkerClusterGroup)', '(0, _reactLeaflet.withLeaflet)' is undefined)`
in _node_modules/react-leaflet-markercluster/dist/react-leaflet-markercluster.min.js:126_

I'm using:

```
{
    "leaflet": "^1.5.1",
    "leaflet.markercluster": "^1.4.1",
    "prop-types": "^15.7.2",
    "react-leaflet": "^2.4.0",
    "react-leaflet-markercluster": "^2.0.0-rc3"
}
```

**Comment by YUzhva** [comment]
the v2.0.0 has been released...

Is this error present in the "stable" version?
