### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not object

### ISSUE THREAD

**Issue by JediahDizon** [YUzhva/react-leaflet-markercluster#96]
Duplicate of a closed issue. Though that post mentions updating a library to `2.0.0-rc2`, it did not specify which library was to be updated.

I got everything updated to their latest version. Any help would be appreciated.

**Comment by barbalex** [comment]
I actually managed to unknowingly replace 2.0.0-rc3 with 1.1.8 myself. Caused this exact issue
