### ISSUE TITLE
onClusterClick Error, getAllChildMarkers() is not a function

### ISSUE THREAD

**Issue by DennisWeini** [YUzhva/react-leaflet-markercluster#97]
I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using React
 I've searched through the issues to make sure it's not yet reported
How to reproduce
<MarkerClusterGroup
showCoverageOnHover={true}
iconCreateFunction={createClusterCustomIcon}
onMarkerClick={(marker) => console.log(marker, marker.getLatLng())}
onClusterClick={(cluster) => console.log(cluster, cluster.getAllChildMarkers())}

Everything if working fine, only onClusterClick throws the Error
"TypeError: cluster.getAllChildMarkers is not a function"

I use
"react-leaflet-markercluster": "^2.0.0-rc3",
"react-leaflet": "^2.5.0",
"leaflet": "^1.5.1",
"leaflet.markercluster": "^1.4.1",

**Comment by YUzhva** [comment]
You can try to `console.log` the obj which is passed into `onClucsterClick` and check if `getAllChildMarkers` still presents there:

```javascript
<MarkerClusterGroup
  showCoverageOnHover={true}
  iconCreateFunction={createClusterCustomIcon}
  onClusterClick={(cluster) => console.log('cluster', cluster)}
/>
```

**Comment by DennisWeini** [comment]
![image](https://user-images.githubusercontent.com/56826174/69055565-5b8cde80-0a0e-11ea-984a-e47d78141faf.png)

no its not. Anything I can do here to get it working?

**Comment by YUzhva** [comment]
The official documentation of [Leaflet.markercluster#events](https://github.com/Leaflet/Leaflet.markercluster#events) says:

```javascript
onClusterClick={(cluster) => console.log('cluster child markers', cluster.layer.getAllChildMarkers())}
```

**Comment by DennisWeini** [comment]
perfect, thank you very much
