### ISSUE TITLE
getAllChildMarkers() returns wrong Markers

### ISSUE THREAD

**Issue by DennisWeini** [YUzhva/react-leaflet-markercluster#98]
In my current project, there are 2 Views on the Map:
First: See all Markers
Second: Show only a few Markers (depends on active Company)

in the first View, the iconCreateFunction works fine, and it colorizes all Cluste-Icons. In my second View, the getAllChildMarkers() still gives me all Markers instead of only a selected few. 

Code: 
```
let markersInCluster = cluster.getAllChildMarkers()
const warning = this.props.stations.filter(v =>  Math.round((v.pIst / v.pNenn) * 100) >= 50)
console.log("warning: " + warning.map(v => v.name))


  const stations = markersInCluster.find((marker) => {
    const found = warning.find((station) => {
      //console.log(station.name)
      //console.log(marker.options.name)
      return station.lng === marker.options.position[1]
    });
    console.log('Found: ', found)
    return found
  }) 
```

This is how I render the Clusters:

```
<MarkerClusterGroup
             showCoverageOnHover={true}
             iconCreateFunction={this.createClusterCustomIcon}
             //onMarkerClick={(marker) => console.log(marker, marker.getLatLng())}
             //onClusterClick={createClusterClick}
             spiderfyDistanceMultiplier={2}

             //onClusterClick={(cluster) => console.log(cluster, cluster.layer.getAllChildMarkers())}
             /*spiderfyOnMaxZoom={true}
             spiderLegPolylineOptions={{
              weight: 2,
              opacity: 1,
              color: '#05C985'
            }}*/
            removeOutsideVisibleBounds={true}
             >
            {this.props.stations.map((station, index) => {
              const load = Math.round((station.pIst / station.pNenn) * 100)
              return (

                <Marker
                  key={index}
                 // backgroundColor={this.getStateMarker(station.name, load)}
                 // fillColor= {this.getMarkerColor(load)}
                  position={[station.lat, station.lng]}
                  icon={this.getStateMarker(station.name, load)}
                  calc={load}
                  companyLocation={station.location}
                  name={station.name}

                 // fillOpacity={0.5}
                 // stroke={true}
                  onClick={(e) => this.onCircleClick(e, station)}
                >

                  <Tooltip direction="right" opacity={1}>
                    <span>{station.location + " / " + station.name + ": " + load + " %"}</span>
                  </Tooltip>
                </Marker>

              )
            })}
           </MarkerClusterGroup>
```

Is there something I forgot?

**Comment by YUzhva** [comment]
Is that issue could be related to #97 

https://github.com/YUzhva/react-leaflet-markercluster/issues/97#issuecomment-555021846

❓

**Comment by DennisWeini** [comment]
no :D I get always all Markers back instead of just the ones who are active to see on the map. The function even returns the markers, who are not rendered anymore.

**Comment by DennisWeini** [comment]
in
`onClusterClick={(cluster) => console.log(cluster, cluster.layer.getAllChildMarkers())}`
its working fine, just in the
`iconCreateFunction={this.createClusterCustomIcon}`
its not working. there it gives me all markers & clusters, but there are only a few on the map

**Comment by derekrprice** [comment]
I think that this ticket needs to be reopened.  I'm seeing a very similar issue to what @DennisWeini described.  After applying a filter rendered in much the same way, I am getting iconCreateFunction callbacks for all the original Markers.  Worse, what should be filtered icon groups appear to be applied on the map over the wrong Markers.  I found the [markers.refreshMarkers function](https://github.com/Leaflet/Leaflet.markercluster#refreshing-the-clusters-icon) in the Leaflet docs that appears to be needed when children marker data is updated.  Does this need to be accessible (or handled) from the React Leaflet MarkerCluster?

**Comment by derekrprice** [comment]
I managed to find the `refershClusters()` method at `markersRef.current.leafletElement.refreshClusters()`, but calling it on update didn't fix the problem.  There must be something else.

**Comment by derekrprice** [comment]
I solved this.  Another developer had used an [array index for the `key`](https://reactjs.org/docs/lists-and-keys.html#keys) of the markers, which was causing some strange, but not unexpected, caching issues for React.

**Comment by TimMcCauley** [comment]
Related https://github.com/yuzhva/react-leaflet-markercluster/issues/149#issuecomment-854920761

**Comment by CharlyPoppins** [comment]
Hi @derekrprice

How do you manage to access to refreshClusters() from <MarkerClusterGroup> ?
